In [1]:
import pandas as pd
import re

In [2]:
sh_sentiment = pd.read_excel(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\Tính 20.08.2024.xlsx", sheet_name='Sentiment')
sh_relevant = pd.read_excel(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\Tính 20.08.2024.xlsx", sheet_name='Relevant')
sh_channel = pd.read_excel(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\Tính 20.08.2024.xlsx", sheet_name='Channel')

# Phân tích biến

Sheet Sentiment

In [3]:
sh_sentiment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16664 entries, 0 to 16663
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Thương hiệu       16664 non-null  object
 1   Ngành hàng        16664 non-null  object
 2   Sản phẩm          16664 non-null  object
 3   Thời gian         16664 non-null  datetime64[ns]
 4   Tuần              16664 non-null  object
 5   Positive          11297 non-null  float64
 6   Neutral           16392 non-null  float64
 7   Negative          5572 non-null   float64
 8   Blank             5942 non-null   float64
 9   Total after       16664 non-null  float64
 10  Blank.1           16663 non-null  float64
 11  Total             16664 non-null  float64
 12  Buzzes thêm       334 non-null    float64
 13  Sum of comments   12683 non-null  float64
 14  Sum of shares     12683 non-null  float64
 15  Positive new      16580 non-null  float64
 16  Neutral new       16664 non-null  float64
 17  Negative new      16450 non-null  float64
 18  Total new         16664 non-null  float64
 19  Check Total Buzz  16664 non-null  int64
 20  Ghi chú           508 non-null    object
 21  Số campaign       192 non-null    object
 22  Phân loại         16664 non-null  object
dtypes: datetime64[ns](1), float64(14), int64(1), object(7)
memory usage: 2.9+ MB

In [4]:
object_columns = list(sh_sentiment.select_dtypes(['object']).columns)
object_columns

['Thương hiệu',
 'Ngành hàng',
 'Sản phẩm',
 'Tuần',
 'Ghi chú',
 'Số campaign',
 'Phân loại']

In [5]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_sentiment[column].unique()), "unique values", "\t & \t", 
          sh_sentiment[column].notnull().sum(), "non-null values\t", 
          round(100* sh_sentiment[column].notnull().sum()/len(sh_sentiment[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 16664 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 16664 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
276 unique values 	 & 	 16664 non-null values	 100.0 % non-null
*, Column:  Tuần
94 unique values 	 & 	 16664 non-null values	 100.0 % non-null
*, Column:  Ghi chú
300 unique values 	 & 	 508 non-null values	 3.05 % non-null
*, Column:  Số campaign
109 unique values 	 & 	 192 non-null values	 1.15 % non-null
*, Column:  Phân loại
18 unique values 	 & 	 16664 non-null values	 100.0 % non-null

In [6]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_sentiment[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        4358
TH True Milk    1866
Nutifood        1741
Nutricare       1495
Vitadairy       1427
Nestlé          1279
FCV              872
IDP              736
Mead Johnson     638
Abbott           564
Vinasoy          339
Đà Lạt Milk      307
Hipp             282
Fonterra         263
Yakult           188
Betagen          187
Hoff             122
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       6141
SN       2946
SC       2260
BRAND    1398
NGK       991
SĐN       954
SĐ        574
KEM       544
BAD       331
BDD       198
BƠ         89
PM         73
ĐƯỜNG      70
FOOD       59
Brand      30
TUNL        6
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
ColosBaby                   98
Vinamilk 100%               96
Thương hiệu TH True Milk    94
Vinamilk Fino               94
Nan                         94
                            ..
Leanmax Colostrum            1
Vinamilk Platinum            1
Vinamilk Probeauty           1
Vinamilk My Joy              1
GrandCare                    1
Name: Sản phẩm, Length: 276, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Tuần
08/06/2024 - 14/06/2024    215
08/12/2023 - 14/12/2023    212
22/05/2024 - 28/05/2024    210
08/07/24 - 14/07/2024      210
01/07/2024 - 07/07/2024    210
                          ...
29/03/2023 - 31/03/2023    123
29/01/2023 - 31/01/2023    120
29/05/2023 - 31/05/2023    118
22/01/2023 - 28/01/2023    114
29/04/2023 - 30/04/2023    111
Name: Tuần, Length: 94, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
rao vặt                                                                                                                 59
minigame trên fanpage                                                                                                   14
Abbott Grow - Dinh Dưỡng Hàng Đầu, Mùa Hè Vui Số 1                                                                       8
không lấy shares ảo                                                                                                      7
rao vặt sản phẩm                                                                                                         6
                                                                                                                        ..
tuyển dụng                                                                                                               1
minigame trên fanpage http://facebook.com/1480930495492638_717522560403119                                               1
bài viết quảng bá sản phẩm                                                                                               1
bị thiếu post livestream LofMalto - Lead with Lof Dance Festival http://facebook.com/110970055031636_849988109906185     1
2000 positive Colosbaby - Sữa Non Ngày Đầu                                                                               1
Name: Ghi chú, Length: 299, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Số campaign
5000                                                                   15
1000                                                                    7
800                                                                     6
#YomostVFLSummer2023 #MotCamGiacRatYomost #Yomost                       5
3000                                                                    5
                                                                       ..
1500: #MILOBich #MILOBichTietKiem #MILO #MILOVietNam                    1
1000: #NANSupremePro3 #nguanguycodiung #Tangdekhang #danggoitienloi     1
2500: #NutrenJunior #TangTruong3Chuan #NestléHealthScience              1
#NestleS26Ultima3 #ChonDinhDuongKhoaHoc #TangTocDoKetNoiNaoBo           1
150000                                                                  1
Name: Số campaign, Length: 108, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Phân loại
SBTE     4267
SN       2946
SBNL     1869
BRAND    1428
SCU      1354
NGK       991
SĐN       942
SCA       906
SĐ        574
KEM       544
BAD       331
BDD       198
BƠ         89
PM         73
ĐƯỜNG      70
FOOD       59
TUNL       18
SB          5
Name: Phân loại, dtype: int64
----------------------------------------------------------------------------------------------------

Sheet Relevant

In [7]:
sh_relevant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3814 entries, 0 to 3813
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Thương hiệu       3814 non-null   object
 1   Ngành hàng        3814 non-null   object
 2   Sản phẩm          3814 non-null   object
 3   Thời gian         3814 non-null   datetime64[ns]
 4   Relevant          3805 non-null   float64
 5   Irrelevant        2368 non-null   float64
 6   Blank             1412 non-null   float64
 7   Total after       3814 non-null   int64
 8   Total             3814 non-null   float64
 9   Buzzes thêm       200 non-null    float64
 10  Relevant new      3814 non-null   float64
 11  Irrelevant new    3814 non-null   float64
 12  Total new         3814 non-null   float64
 13  Check Total Buzz  3814 non-null   int64
 14  Ghi chú           4 non-null      object
dtypes: datetime64[ns](1), float64(8), int64(2), object(4)
memory usage: 447.1+ KB

In [8]:
object_columns = list(sh_relevant.select_dtypes(['object']).columns)
object_columns

['Thương hiệu', 'Ngành hàng', 'Sản phẩm', 'Ghi chú']

In [9]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_relevant[column].unique()), "unique values", "\t & \t", 
          sh_relevant[column].notnull().sum(), "non-null values\t", 
          round(100* sh_relevant[column].notnull().sum()/len(sh_relevant[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 3814 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 3814 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
277 unique values 	 & 	 3814 non-null values	 100.0 % non-null
*, Column:  Ghi chú
5 unique values 	 & 	 4 non-null values	 0.1 % non-null

In [10]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_relevant[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        1002
Nutricare        423
Nutifood         419
TH True Milk     399
Vitadairy        310
Nestlé           284
FCV              198
IDP              163
Mead Johnson     141
Abbott           114
Vinasoy           73
Đà Lạt Milk       66
Hipp              57
Fonterra          56
Betagen           45
Yakult            38
Hoff              26
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       1456
SN        637
SC        493
BRAND     301
NGK       244
SĐN       222
SĐ        130
KEM       113
BAD        78
BDD        52
ĐƯỜNG      21
BƠ         19
PM         17
FOOD       13
Kem        12
TUNL        6
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
Vinamilk Susu                   20
ColosBaby                       20
Thương hiệu Abbott              19
Nan Optipro 4                   19
Vinamilk Ngôi Sao Phương Nam    19
                                ..
Vinamilk Platinum                1
Nunest Kid                       1
GrandCare                        1
Vinamilk Greek Yoghurt           1
Ensure                           1
Name: Sản phẩm, Length: 277, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
yes, minigame, fanpage                1
#DinhDuongChatLuong #ViConLaSo1       1
#VềNhàĐónVuLan và  #VuiSongMoiNgay    1
campaign Bé Lành Học Nhanh            1
Name: Ghi chú, dtype: int64
----------------------------------------------------------------------------------------------------

Sheet Channel

In [11]:
sh_channel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3813 entries, 0 to 3812
Data columns (total 36 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Thương hiệu                   3813 non-null   object
 1   Ngành hàng                    3813 non-null   object
 2   Sản phẩm                      3813 non-null   object
 3   Thời gian                     3813 non-null   datetime64[ns]
 4   Fanpage                       2276 non-null   float64
 5   FB page                       3271 non-null   float64
 6   FB user                       3336 non-null   float64
 7   FB group                      3288 non-null   float64
 8   Tiktok                        1969 non-null   float64
 9   Forum                         776 non-null    float64
 10  News                          1187 non-null   float64
 11  Youtube                       1010 non-null   float64
 12  E-commerce                    268 non-null    float64
 13  Instagram                     52 non-null     float64
 14  Threads                       187 non-null    float64
 15  Linkedin                      60 non-null     float64
 16  Total after                   3813 non-null   int64
 17  Total                         3813 non-null   float64
 18  Total FB và Total FB, Tiktok  3813 non-null   float64
 19  Buzzes thêm                   287 non-null    float64
 20  Fanpage new                   3787 non-null   float64
 21  FB page new                   3787 non-null   float64
 22  FB user new                   3787 non-null   float64
 23  FB group new                  3787 non-null   float64
 24  Tiktok new                    3809 non-null   float64
 25  Forum new                     3813 non-null   int64
 26  News new                      3813 non-null   int64
 27  Youtube new                   3813 non-null   int64
 28  E-commerce new                3813 non-null   int64
 29  Instagram new                 3813 non-null   int64
 30  Threads new                   3813 non-null   int64
 31  Linkedin new                  3813 non-null   int64
 32  Total new                     3813 non-null   float64
 33  Check Total Buzz              3813 non-null   int64
 34  Total Facebook                3813 non-null   float64
 35  Ghi chú                       5 non-null      object
dtypes: datetime64[ns](1), float64(22), int64(9), object(4)
memory usage: 1.0+ MB

In [12]:
object_columns = list(sh_channel.select_dtypes(['object']).columns)
object_columns

['Thương hiệu', 'Ngành hàng', 'Sản phẩm', 'Ghi chú']

In [13]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_channel[column].unique()), "unique values", "\t & \t", 
          sh_channel[column].notnull().sum(), "non-null values\t", 
          round(100* sh_channel[column].notnull().sum()/len(sh_channel[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 3813 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 3813 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
276 unique values 	 & 	 3813 non-null values	 100.0 % non-null
*, Column:  Ghi chú
6 unique values 	 & 	 5 non-null values	 0.13 % non-null

In [14]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_sentiment[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        4358
TH True Milk    1866
Nutifood        1741
Nutricare       1495
Vitadairy       1427
Nestlé          1279
FCV              872
IDP              736
Mead Johnson     638
Abbott           564
Vinasoy          339
Đà Lạt Milk      307
Hipp             282
Fonterra         263
Yakult           188
Betagen          187
Hoff             122
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       6141
SN       2946
SC       2260
BRAND    1398
NGK       991
SĐN       954
SĐ        574
KEM       544
BAD       331
BDD       198
BƠ         89
PM         73
ĐƯỜNG      70
FOOD       59
Brand      30
TUNL        6
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
ColosBaby                   98
Vinamilk 100%               96
Thương hiệu TH True Milk    94
Vinamilk Fino               94
Nan                         94
                            ..
Leanmax Colostrum            1
Vinamilk Platinum            1
Vinamilk Probeauty           1
Vinamilk My Joy              1
GrandCare                    1
Name: Sản phẩm, Length: 276, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
rao vặt                                                                                                                 59
minigame trên fanpage                                                                                                   14
Abbott Grow - Dinh Dưỡng Hàng Đầu, Mùa Hè Vui Số 1                                                                       8
không lấy shares ảo                                                                                                      7
rao vặt sản phẩm                                                                                                         6
                                                                                                                        ..
tuyển dụng                                                                                                               1
minigame trên fanpage http://facebook.com/1480930495492638_717522560403119                                               1
bài viết quảng bá sản phẩm                                                                                               1
bị thiếu post livestream LofMalto - Lead with Lof Dance Festival http://facebook.com/110970055031636_849988109906185     1
2000 positive Colosbaby - Sữa Non Ngày Đầu                                                                               1
Name: Ghi chú, Length: 299, dtype: int64
----------------------------------------------------------------------------------------------------

# Tổng quan

In [15]:
month = "07/2024"
year = "2024"

pre_month = '07/2023'
pre_ytd = ['01/2023','02/2023','03/2023','04/2023','05/2023','06/2023','07/2023']
pre_year = "2023"

In [16]:
exclude_brands = ["Hoff", "Betagen", "Yakult"]
bdd = ['BAD', 'BDD']

In [17]:
#Thị phần ngành sữa theo Tháng năm 2024
filtered_sh_sentiment_mon = sh_sentiment[(sh_sentiment["Thời gian"] == month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV = filtered_sh_sentiment_mon.groupby(["Thương hiệu"]).agg({"Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
SOV.columns=['month','Total new']
SOV

           month  Total new
0      Vitadairy   777615.0
1         Nestlé   432455.0
2       Vinamilk   404978.0
3         Abbott   140398.0
4       Nutifood   108454.0
5            IDP    61227.0
6   Mead Johnson    58781.0
7   TH True Milk    58345.0
8            FCV    38967.0
9        Vinasoy    27287.0
10          Hipp    18556.0
11     Nutricare     7470.0
12   Đà Lạt Milk     6570.0
13      Fonterra     4328.0

In [18]:
#Thị phần ngành sữa theo tháng năm 2023

filtered_sh_sentiment_pre_mon = sh_sentiment[(sh_sentiment["Thời gian"] == pre_month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV_pre = filtered_sh_sentiment_pre_mon.groupby(["Thương hiệu"]).agg({"Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
SOV_pre.columns=['pre_month','Total new']
SOV_pre

       pre_month  Total new
0       Vinamilk   518277.0
1         Nestlé   444269.0
2            FCV   125129.0
3       Nutifood    73964.0
4         Abbott    47307.0
5   TH True Milk    29923.0
6      Vitadairy    25734.0
7            IDP    24313.0
8   Mead Johnson    20759.0
9        Vinasoy    11491.0
10     Nutricare     7656.0
11      Fonterra     4679.0
12          Hipp     1659.0
13   Đà Lạt Milk      684.0

In [19]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl') as writer:
    # Write df1 starting at cell A1
    SOV.to_excel(writer, sheet_name='month_brand', startrow=0, startcol=0, index=False)
    
    # Write df2 starting at cell A5 (5th row)
    SOV_pre.to_excel(writer, sheet_name='month_brand', startrow=0, startcol=3, index=False)

In [20]:
#Sentiment các brand theo Tháng năm 2024
filtered_sh_sentiment_mon = sh_sentiment[(sh_sentiment["Thời gian"] == month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
brand_sent = filtered_sh_sentiment_mon.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
brand_sent.columns=['month','Positive','Neutral','Negative','Total new']
brand_sent

           month  Positive   Neutral  Negative  Total new
0      Vitadairy  709336.0   68155.0     124.0   777615.0
1         Nestlé  398258.0   34190.0       8.0   432455.0
2       Vinamilk  223563.0  181196.0     219.0   404978.0
3         Abbott   66934.0   73191.0     274.0   140398.0
4       Nutifood   28155.0   80252.0      47.0   108454.0
5            IDP   30837.0   30032.0     357.0    61227.0
6   Mead Johnson   30852.0   27741.0     188.0    58781.0
7   TH True Milk   10600.0   47619.0     126.0    58345.0
8            FCV   11738.0   27091.0     138.0    38967.0
9        Vinasoy   14087.0   13185.0      15.0    27287.0
10          Hipp    3966.0   14573.0      17.0    18556.0
11     Nutricare    1041.0    6421.0       8.0     7470.0
12   Đà Lạt Milk     650.0    5919.0       1.0     6570.0
13      Fonterra    1370.0    2958.0       0.0     4328.0

In [21]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    brand_sent.to_excel(writer, index=False, sheet_name='month_brand_sent')

In [22]:
#Sắc thái thảo luận của các thương hiệu pre-YTD
filtered_sh_sentiment_pre_ytd = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
brand_sent_pre_ytd = filtered_sh_sentiment_pre_ytd.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
brand_sent_pre_ytd.columns =['preYTD','Positive','Neutral','Negative','Total new']
brand_sent_pre_ytd

          preYTD   Positive   Neutral  Negative  Total new
0       Vinamilk  1950457.0  338095.0    2859.0  2291411.0
1         Nestlé   962161.0  230206.0     606.0  1192974.0
2         Abbott   322700.0  324879.0    1941.0   649520.0
3            FCV   373260.0  128987.0     284.0   502531.0
4       Nutifood   438020.0   35606.0     291.0   473917.0
5            IDP    67933.0   73111.0     477.0   141521.0
6   Mead Johnson   121317.0   19684.0     425.0   141425.0
7   TH True Milk    38522.0   90991.0     990.0   130503.0
8        Vinasoy    60967.0   38086.0    3594.0   102647.0
9      Vitadairy    39914.0   49201.0     547.0    89661.0
10      Fonterra     4138.0    8484.0      14.0    12636.0
11     Nutricare     3630.0    4013.0      14.0     7656.0
12          Hipp     1505.0    4279.0      57.0     5841.0
13   Đà Lạt Milk      938.0    2649.0      11.0     3598.0

In [23]:
#Category_pre-YTD
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands))]
cate = filtered_sh_sentiment.pivot_table(index='Thương hiệu', columns='Ngành hàng', values='Total new', aggfunc='sum').round(decimals=0).fillna(0)
cate['Total'] = cate.sum(axis=1)
cate = cate.sort_values(by="Total",ascending=False)
cate.reset_index(inplace=True)
cate['BDD'] = cate[['BDD','BAD']].sum(axis=1)
cate['Khác'] = cate['Total'] - cate[['SN','SC','SB','BDD','SĐ','SĐN']].sum(axis=1)
cate = cate[['Thương hiệu','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']]
cate.columns = ['pre_YTD','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']
cate

,pre_YTD,SN,SC,SB,BDD,SĐ,SĐN,Khác,Total
0,Vinamilk,731839.0,856597.0,535071.0,3863.0,33278.0,16135.0,114628.0,2291411.0
1,Nestlé,655673.0,8038.0,418757.0,17058.0,0.0,0.0,93448.0,1192974.0
2,Abbott,0.0,0.0,629345.0,0.0,0.0,0.0,20175.0,649520.0
3,FCV,57908.0,128873.0,296187.0,0.0,264.0,0.0,19299.0,502531.0
4,Nutifood,15480.0,1459.0,416672.0,9.0,90.0,1320.0,38887.0,473917.0
5,IDP,121415.0,5022.0,0.0,0.0,0.0,0.0,15084.0,141521.0
6,Mead Johnson,0.0,0.0,137215.0,0.0,0.0,0.0,4210.0,141425.0
7,TH True Milk,43169.0,11973.0,2509.0,0.0,0.0,4817.0,68035.0,130503.0
8,Vinasoy,0.0,14688.0,0.0,0.0,0.0,63956.0,24003.0,102647.0
9,Vitadairy,10899.0,0.0,69600.0,0.0,0.0,0.0,9162.0,89661.0
10,Fonterra,0.0,0.0,10962.0,0.0,0.0,0.0,1674.0,12636.0
11,Nutricare,1158.0,24.0,6208.0,21.0,0.0,0.0,245.0,7656.0
12,Hipp,0.0,0.0,2760.0,1129.0,0.0,0.0,1952.0,5841.0
13,Đà Lạt Milk,1787.0,1283.0,0.0,0.0,0.0,0.0,528.0,3598.0

In [24]:
#Số buzz theo tuần
filtered_sh_sentiment = sh_sentiment[((sh_sentiment["Thời gian"] == month)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
week = filtered_sh_sentiment.pivot_table(index='Tuần', columns='Thương hiệu', values='Total new', aggfunc='sum').round(decimals=0)
column_sums = week.sum(axis=0, numeric_only=True)
week.loc['Total'] = week.sum(numeric_only=True)
week.reset_index(inplace=True)
total_values = week.loc[week['Tuần'] == 'Total'].drop(columns=['Tuần']).iloc[0]
sorted_columns = total_values.sort_values(ascending=False).index
sorted_columns = ['Tuần'] + sorted_columns.tolist()
week = week[sorted_columns]
week

Thương hiệu,Tuần,Vitadairy,Nestlé,Vinamilk,Abbott,Nutifood,IDP,Mead Johnson,TH True Milk,FCV,Vinasoy,Hipp,Nutricare,Đà Lạt Milk,Fonterra
0,01/07/2024 - 07/07/2024,22972.0,103793.0,66168.0,38229.0,26459.0,13465.0,5287.0,15661.0,24948.0,10919.0,2928.0,1433.0,851.0,1033.0
1,08/07/24 - 14/07/2024,79426.0,47800.0,59774.0,32965.0,23004.0,12417.0,8947.0,10311.0,5402.0,4102.0,3366.0,1804.0,1054.0,768.0
2,15/07/2024 - 21/07/2024,192048.0,41986.0,133730.0,20665.0,22828.0,12805.0,36406.0,10858.0,4253.0,8039.0,4435.0,2358.0,3497.0,723.0
3,22/07/2024 - 28/07/2024,200666.0,51328.0,112498.0,17746.0,20116.0,17232.0,4332.0,13175.0,3480.0,2624.0,5304.0,1489.0,899.0,620.0
4,29/07/2024 - 31/07/2024,282503.0,187548.0,32808.0,30793.0,16047.0,5308.0,3809.0,8340.0,884.0,1603.0,2523.0,386.0,269.0,1184.0
5,Total,777615.0,432455.0,404978.0,140398.0,108454.0,61227.0,58781.0,58345.0,38967.0,27287.0,18556.0,7470.0,6570.0,4328.0

In [25]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    week.to_excel(writer, index=False, sheet_name='week')

In [26]:
sh_relevant["Thời gian"] = sh_relevant["Thời gian"].astype(str)
sh_sentiment["Thời gian"] = sh_sentiment["Thời gian"].astype(str)
sh_channel["Thời gian"] = sh_channel["Thời gian"].astype(str)

In [27]:
#Sắc thái thảo luận của các thương hiệu YTD
filtered_sh_sentiment_YTD = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
sentiment_brand = filtered_sh_sentiment_YTD.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
sentiment_brand.columns =['YTD','Positive','Neutral','Negative','Total new']
sentiment_brand

             YTD   Positive    Neutral  Negative  Total new
0       Vinamilk  4422046.0  1484566.0    1456.0  5908068.0
1         Nestlé  3428545.0   213085.0     366.0  3641996.0
2       Nutifood  2653579.0   205001.0     538.0  2859118.0
3         Abbott   779277.0   543751.0   14419.0  1337447.0
4            IDP   908286.0   152963.0    4952.0  1066201.0
5      Vitadairy   807912.0   219564.0     346.0  1027822.0
6   TH True Milk    58053.0   340371.0    1859.0   400284.0
7   Mead Johnson   208733.0   112510.0     714.0   321957.0
8            FCV    65525.0   245267.0     603.0   311395.0
9       Fonterra   123633.0    76020.0      70.0   199722.0
10       Vinasoy   101995.0    73691.0     238.0   175924.0
11          Hipp    20789.0    75113.0     168.0    96070.0
12     Nutricare     8060.0    47174.0      62.0    55296.0
13   Đà Lạt Milk     1288.0    24600.0      12.0    25900.0

In [28]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode ='a',if_sheet_exists='overlay') as writer:
    brand_sent_pre_ytd.to_excel(writer, sheet_name='YTD_brand_sent', startrow=0, startcol=0, index=False)
    sentiment_brand.to_excel(writer, sheet_name='YTD_brand_sent', startrow=0, startcol=6, index=False)

In [29]:
#Category
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands))]
cate_ytd = filtered_sh_sentiment.pivot_table(index='Thương hiệu', columns='Ngành hàng', values='Total new', aggfunc='sum').round(decimals=0).fillna(0)
cate_ytd['Total'] = cate_ytd.sum(axis=1)
cate_ytd = cate_ytd.sort_values(by="Total",ascending=False)
cate_ytd.reset_index(inplace=True)
cate_ytd['BDD'] = cate_ytd[['BDD','BAD']].sum(axis=1)
cate_ytd['Khác'] = cate_ytd['Total'] - cate_ytd[['SN','SC','SB','BDD','SĐ','SĐN']].sum(axis=1)
cate_ytd = cate_ytd[['Thương hiệu','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']]
cate_ytd.columns = ['YTD','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']
cate_ytd

,YTD,SN,SC,SB,BDD,SĐ,SĐN,Khác,Total
0,Vinamilk,390884.0,2904299.0,1882842.0,8317.0,463075.0,18013.0,240638.0,5908068.0
1,Nestlé,1846073.0,5016.0,1555954.0,10800.0,0.0,0.0,224153.0,3641996.0
2,Nutifood,41365.0,4321.0,2770687.0,985.0,1060.0,1896.0,38804.0,2859118.0
3,Abbott,0.0,0.0,1318417.0,0.0,0.0,0.0,19030.0,1337447.0
4,IDP,1049855.0,12729.0,0.0,0.0,0.0,0.0,3617.0,1066201.0
5,Vitadairy,31079.0,0.0,959444.0,0.0,0.0,0.0,37299.0,1027822.0
6,TH True Milk,81801.0,44977.0,19220.0,0.0,0.0,26074.0,228212.0,400284.0
7,Mead Johnson,0.0,0.0,320904.0,0.0,0.0,0.0,1053.0,321957.0
8,FCV,60314.0,198937.0,43596.0,0.0,7546.0,0.0,1002.0,311395.0
9,Fonterra,0.0,0.0,199488.0,0.0,0.0,0.0,234.0,199722.0
10,Vinasoy,0.0,8413.0,0.0,0.0,0.0,158808.0,8703.0,175924.0
11,Hipp,0.0,0.0,68844.0,9141.0,0.0,0.0,18085.0,96070.0
12,Nutricare,3981.0,648.0,39780.0,225.0,0.0,129.0,10533.0,55296.0
13,Đà Lạt Milk,21192.0,2762.0,0.0,0.0,0.0,0.0,1946.0,25900.0

In [30]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode ='a',if_sheet_exists='overlay') as writer:
    cate.to_excel(writer, sheet_name='YTD_cate', startrow=0, startcol=0, index=False)
    cate_ytd.to_excel(writer, sheet_name='YTD_cate', startrow=0, startcol=12, index=False)

In [31]:
#Relevant thảo luận của các thương hiệu YTD
filtered_sh_relevant_YTD = sh_relevant[(sh_relevant["Thời gian"].str.contains(year,na=False)) & ~sh_relevant["Thương hiệu"].isin(exclude_brands)]
relevant_brand = filtered_sh_relevant_YTD.groupby(["Thương hiệu"]).agg({"Relevant new": "sum","Irrelevant new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
relevant_brand

     Thương hiệu  Relevant new  Irrelevant new  Total new
0       Vinamilk     5527607.0        380461.0  5908068.0
1         Nestlé     3622772.0         19224.0  3641996.0
2       Nutifood     2818952.0         40166.0  2859118.0
3         Abbott     1215703.0        121744.0  1337447.0
4            IDP     1049831.0         16370.0  1066201.0
5      Vitadairy     1013418.0         14404.0  1027822.0
6   TH True Milk      338430.0         61854.0   400284.0
7   Mead Johnson      306916.0         15041.0   321957.0
8            FCV      293542.0         17853.0   311395.0
9       Fonterra      176975.0         22747.0   199722.0
10       Vinasoy      164317.0         11607.0   175924.0
11          Hipp       85231.0         10839.0    96070.0
12     Nutricare       52022.0          3274.0    55296.0
13   Đà Lạt Milk       25795.0           105.0    25900.0

In [32]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    relevant_brand.to_excel(writer, index=False, sheet_name='YTD_rlv')

In [33]:
# Thảo luận của các thương hiệu theo kênh YTD
filtered_sh_channel_YTD = sh_channel[(sh_channel["Thời gian"].str.contains(year,na=False)) & ~sh_channel["Thương hiệu"].isin(exclude_brands)]
channel_brand = filtered_sh_channel_YTD.groupby(["Thương hiệu"]).agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()  
channel_brand["Khác"] = channel_brand["Total new"] - channel_brand.drop(columns=["Thương hiệu", "Total new"]).sum(axis=1)
channel_brand = channel_brand[['Thương hiệu','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
channel_brand

,Thương hiệu,Fanpage new,FB page new,FB user new,FB group new,Tiktok new,Forum new,News new,Youtube new,Khác,Total new
0,Vinamilk,555202.0,1320827.0,3214587.0,555802.0,217617.0,15259,12577,14424,1773.0,5908068.0
1,Nestlé,244522.0,1336149.0,1578327.0,459432.0,20793.0,241,1489,174,869.0,3641996.0
2,Nutifood,1922918.0,182650.0,504849.0,211784.0,33778.0,31,740,606,1762.0,2859118.0
3,Abbott,390983.0,273255.0,406318.0,239852.0,26288.0,312,306,124,9.0,1337447.0
4,IDP,177750.0,88505.0,450086.0,38145.0,301560.0,128,629,8480,918.0,1066201.0
5,Vitadairy,51000.0,364273.0,400586.0,196513.0,14483.0,46,99,342,480.0,1027822.0
6,TH True Milk,59138.0,152937.0,84141.0,81710.0,18173.0,347,2188,1471,179.0,400284.0
7,Mead Johnson,983.0,187815.0,40514.0,86374.0,5774.0,69,128,63,237.0,321957.0
8,FCV,30779.0,112982.0,58918.0,75849.0,32223.0,71,133,403,37.0,311395.0
9,Fonterra,13725.0,98359.0,78562.0,3562.0,5416.0,6,49,40,3.0,199722.0
10,Vinasoy,101588.0,20482.0,34378.0,16171.0,2713.0,13,324,237,18.0,175924.0
11,Hipp,295.0,27544.0,9638.0,54426.0,3879.0,25,2,13,248.0,96070.0
12,Nutricare,4370.0,6570.0,20624.0,16085.0,7318.0,0,110,141,78.0,55296.0
13,Đà Lạt Milk,306.0,6176.0,7661.0,10960.0,529.0,18,93,43,114.0,25900.0

In [34]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    channel_brand.to_excel(writer, index=False, sheet_name='YTD_channel')

# Ngành hàng

Sentiment, Relevant

In [35]:
def process_data(df, columns, nganh_hang, year):
    filtered_df = df[(df["Ngành hàng"] == nganh_hang) & (df["Thời gian"].str.contains(year, na=False))]
    
    grouped_df = filtered_df.groupby(["Sản phẩm"]).agg(columns).sort_values(by="Total new", ascending=False).reset_index().round()
    
    top_13 = grouped_df.head(13)
    khac = grouped_df.iloc[13:].agg(columns).to_frame().transpose()
    
    result_df = pd.concat([top_13, khac], ignore_index=True)
    result_df.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
    
    return result_df


# Define columns for Sentiment
sentiment_columns = { "Total new": "sum", "Positive new": "sum", "Neutral new": "sum", "Negative new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx"
existing_excel = pd.ExcelFile(existing_excel_path)

with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    start_column = 0  # Initialize start column for each df
    for nganh_hang in nganh_hang_list:
        # Process data for each nganh_hang
        sentiment_data = process_data(sh_sentiment, sentiment_columns, nganh_hang, year)
        
        # Rename the 'Sản phẩm' column to the current 'nganh_hang' value
        sentiment_data.rename(columns={'Sản phẩm': nganh_hang}, inplace=True)
        
        # Display the sentiment_data for debugging
        print(f"Sentiment ({nganh_hang}):")
        print(sentiment_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        sentiment_data.to_excel(writer, sheet_name="Sentiment_Cate", startcol=start_column, index=False)
        
        # Adjust start column for the next DataFrame
        start_column += len(sentiment_data.columns) + 3  # Increment by number of columns + some padding

# Close the existing Excel file
existing_excel.close()

# Define columns for Relevant
relevant_columns = {"Relevant new": "sum","Irrelevant new": "sum","Total new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx"
existing_excel = pd.ExcelFile(existing_excel_path)

with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    start_column = 0  # Initialize start column for each df
    for nganh_hang in nganh_hang_list:
        # Process data for each nganh_hang
        relevant_data = process_data(sh_relevant, relevant_columns, nganh_hang, year)
        
        # Rename the 'Sản phẩm' column to the current 'nganh_hang' value
        relevant_data.rename(columns={'Sản phẩm': nganh_hang}, inplace=True)
        
        # Display the sentiment_data for debugging
        print(f"Relevant ({nganh_hang}):")
        print(relevant_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        relevant_data.to_excel(writer, sheet_name="Relevant_Cate", startcol=start_column, index=False)
        
        # Adjust start column for the next DataFrame
        start_column += len(relevant_data.columns) + 3  # Increment by number of columns + some padding

# Close the existing Excel file
existing_excel.close()

Sentiment (SC):
                           SC  Total new  Positive new  Neutral new  \
0           Sữa chua Vinamilk   851274.0      711377.0     139746.0
1              Vinamilk Probi   737479.0      628939.0     108373.0
2               Vinamilk Susu   659916.0      564427.0      95430.0
3               Vinamilk Hero   654108.0      563540.0      90567.0
4                      Yomost   191505.0       41773.0     149606.0
5             Sữa chua Yakult    64187.0       22833.0      41249.0
6              TH True Yogurt    33612.0        5018.0      28373.0
7               Sữa chua Hoff    30349.0        1310.0      28671.0
8                        Veyo     8413.0        6517.0       1895.0
9             Sữa chua TOPKID     7602.0        1824.0       5737.0
10          Sữa chua ăn Ba Vì     5905.0         730.0       5173.0
11      Sữa chua uống LIF KUN     5739.0         352.0       5369.0
12  Sữa chua uống Nestle Yogu     4809.0          14.0       4795.0
13              Sản phẩm khác    26880.0        4770.0      22090.0

    Negative new
0          151.0
1          167.0
2           59.0
3            1.0
4          125.0
5          105.0
6          221.0
7          369.0
8            1.0
9           41.0
10           1.0
11          18.0
12           0.0
13          19.0

==================================================

Sentiment (SN):
                           SN  Total new  Positive new  Neutral new  \
0                        Milo  1828459.0     1784728.0      43556.0
1                     LOF KUN   973214.0      853504.0     115378.0
2               Vinamilk 100%   283488.0      248919.0      34557.0
3      Sữa lúa mạch Lof Malto    61035.0       47060.0      13581.0
4         Vinamilk Green Farm    60680.0       48151.0      12520.0
5       Sữa tươi TH True Milk    43940.0        7179.0      36361.0
6   Sữa tươi Dutch Lady (RTD)    37952.0        2168.0      35740.0
7                    Ovaltine    22360.0       15786.0       6528.0
8        Sữa tươi Đà Lạt Milk    21192.0        1058.0      20124.0
9               Vinamilk Fino    20657.0        8191.0      12373.0
10            Sữa nước Nestlé    17614.0         417.0      17197.0
11          Sữa trái cây Oggi    15650.0        2219.0      13429.0
12   Sữa non Colos Fresh Milk    15257.0       12045.0       3212.0
13              Sản phẩm khác   125046.0       30615.0      93805.0

    Negative new
0          175.0
1         4332.0
2           12.0
3          394.0
4            9.0
5          400.0
6           45.0
7           47.0
8           10.0
9           93.0
10           0.0
11           2.0
12           0.0
13         628.0

==================================================

Sentiment (SB):
                           SB  Total new  Positive new  Neutral new  \
0                   Nuvi Grow  1852078.0     1830983.0      21091.0
1                   Grow Plus   880980.0      791397.0      89350.0
2   Vinamilk Dielac Grow Plus   784300.0      388260.0     396027.0
3                  Colos gain   706580.0      671895.0      34589.0
4               Nan Optipro 4   611943.0      600644.0      11297.0
5         Abbott Grow Vietnam   535736.0      317596.0     217637.0
6          Vinamilk Yoko Gold   405780.0      391159.0      14599.0
7               S-26 Ultima 3   367538.0      319830.0      47660.0
8             Similac Vietnam   347562.0      195268.0     151148.0
9           Pediasure Vietnam   303012.0      206818.0      95463.0
10                        Nan   291004.0      238027.0      52908.0
11           Vinamilk Optimum   245908.0      214909.0      30821.0
12      Vinamilk Sure Prevent   217474.0      205754.0      11717.0
13              Sản phẩm khác  1629281.0      995146.0     621499.0

    Negative new
0            4.0
1          234.0
2           13.0
3           96.0
4            2.0
5          502.0
6           22.0
7           48.0
8         1146.0
9          731.0
10          69.0
11         178.0
12           3.0
13       12637.0

==================================================

Sentiment (SĐ):
                              SĐ  Total new  Positive new  Neutral new  \
0               Vinamilk Ông thọ   435398.0      189716.0     245575.0
1   Vinamilk Ngôi Sao Phương Nam    17338.0        3454.0      13882.0
2             Sữa đặc Dutch Lady     7317.0         163.0       7154.0
3               Sữa đặc Vinamilk     7050.0         284.0       6766.0
4               Vinamilk Tài lộc     3289.0          56.0       3231.0
5               Sữa đặc Nutifood     1060.0          25.0       1035.0
6               Sữa đặc Hoàn Hảo      229.0           1.0        228.0
7                            NaN        0.0           0.0          0.0
13                 Sản phẩm khác        NaN           NaN          NaN

    Negative new
0          107.0
1            2.0
2            0.0
3            0.0
4            2.0
5            0.0
6            0.0
7            0.0
13           NaN

==================================================

Sentiment (SĐN):
                         SĐN  Total new  Positive new  Neutral new  \
0                       Fami   158760.0       91429.0      67094.0
1                TH True Nut    24901.0        1988.0      22843.0
2         Vinamilk Super Nut     4855.0         493.0       4353.0
3        Vinamilk Hạt Óc Chó     4789.0        1547.0       3208.0
4         Vinamilk Hạnh Nhân     2842.0        1405.0       1434.0
5            Vinamilk Đậu Đỏ     2823.0        1407.0       1414.0
6      Sữa Đậu Nành Vinamilk     2028.0         981.0       1046.0
7      Sữa đậu nành Nutifood     1896.0          97.0       1799.0
8         TH True Light Meal      903.0         206.0        680.0
9   Vinamilk Sữa hạt Cao Đạm      639.0          79.0        560.0
10               TH true OAT      270.0          86.0        184.0
11             Nunut Lục Bảo      129.0           0.0        129.0
12      Sữa đậu nành Vinasoy       48.0           6.0         42.0
13             Sản phẩm khác       37.0           3.0         34.0

    Negative new
0          237.0
1           70.0
2            9.0
3           34.0
4            3.0
5            2.0
6            1.0
7            0.0
8           17.0
9            0.0
10           0.0
11           0.0
12           0.0
13           0.0

==================================================

Relevant (SC):
                           SC  Relevant new  Irrelevant new  Total new
0           Sữa chua Vinamilk      812854.0         38420.0   851274.0
1              Vinamilk Probi      669649.0         67830.0   737479.0
2               Vinamilk Susu      601344.0         58572.0   659916.0
3               Vinamilk Hero      595814.0         58294.0   654108.0
4                      Yomost      185344.0          6161.0   191505.0
5             Sữa chua Yakult       55621.0          8566.0    64187.0
6              TH True Yogurt       30719.0          2893.0    33612.0
7               Sữa chua Hoff       28643.0          1706.0    30349.0
8                        Veyo        7709.0           704.0     8413.0
9             Sữa chua TOPKID        7544.0            58.0     7602.0
10          Sữa chua ăn Ba Vì        5894.0            11.0     5905.0
11      Sữa chua uống LIF KUN        5732.0             7.0     5739.0
12  Sữa chua uống Nestle Yogu        4809.0             0.0     4809.0
13              Sản phẩm khác       25416.0          1464.0    26880.0

==================================================

Relevant (SN):
                           SN  Relevant new  Irrelevant new  Total new
0                        Milo     1813576.0         14883.0  1828459.0
1                     LOF KUN      960865.0         12349.0   973214.0
2               Vinamilk 100%      267179.0         16309.0   283488.0
3      Sữa lúa mạch Lof Malto       58689.0          2346.0    61035.0
4         Vinamilk Green Farm       57244.0          3436.0    60680.0
5       Sữa tươi TH True Milk       43669.0           271.0    43940.0
6   Sữa tươi Dutch Lady (RTD)       33081.0          4871.0    37952.0
7                    Ovaltine       20035.0          2325.0    22360.0
8        Sữa tươi Đà Lạt Milk       21117.0            75.0    21192.0
9               Vinamilk Fino       19416.0          1241.0    20657.0
10            Sữa nước Nestlé       17614.0             0.0    17614.0
11          Sữa trái cây Oggi       14501.0          1149.0    15650.0
12   Sữa non Colos Fresh Milk       15197.0            60.0    15257.0
13              Sản phẩm khác      119538.0          5508.0   125046.0

==================================================

Relevant (SB):
                           SB  Relevant new  Irrelevant new  Total new
0                   Nuvi Grow     1840174.0         11904.0  1852078.0
1                   Grow Plus      860105.0         20875.0   880980.0
2   Vinamilk Dielac Grow Plus      731176.0         53124.0   784300.0
3                  Colos gain      703170.0          3410.0   706580.0
4               Nan Optipro 4      609551.0          2392.0   611943.0
5         Abbott Grow Vietnam      490275.0         45461.0   535736.0
6          Vinamilk Yoko Gold      398413.0          7367.0   405780.0
7               S-26 Ultima 3      367231.0           307.0   367538.0
8             Similac Vietnam      308681.0         38881.0   347562.0
9           Pediasure Vietnam      281402.0         21610.0   303012.0
10                        Nan      290530.0           474.0   291004.0
11           Vinamilk Optimum      241555.0          4353.0   245908.0
12      Vinamilk Sure Prevent      211913.0          5561.0   217474.0
13              Sản phẩm khác     1523300.0        105981.0  1629281.0

==================================================

Relevant (SĐ):
                              SĐ  Relevant new  Irrelevant new  Total new
0               Vinamilk Ông thọ      408440.0         26958.0   435398.0
1   Vinamilk Ngôi Sao Phương Nam       16573.0           765.0    17338.0
2             Sữa đặc Dutch Lady        7317.0             0.0     7317.0
3               Sữa đặc Vinamilk        6997.0            53.0     7050.0
4               Vinamilk Tài lộc        3267.0            22.0     3289.0
5               Sữa đặc Nutifood        1060.0             0.0     1060.0
6               Sữa đặc Hoàn Hảo         229.0             0.0      229.0
7                            NaN           0.0             0.0        0.0
13                 Sản phẩm khác           NaN             NaN        NaN

==================================================

Relevant (SĐN):
                         SĐN  Relevant new  Irrelevant new  Total new
0                       Fami      148701.0         10059.0   158760.0
1                TH True Nut       24852.0            49.0    24901.0
2         Vinamilk Super Nut        4671.0           184.0     4855.0
3        Vinamilk Hạt Óc Chó        4355.0           434.0     4789.0
4         Vinamilk Hạnh Nhân        2500.0           342.0     2842.0
5            Vinamilk Đậu Đỏ        2481.0           342.0     2823.0
6      Sữa Đậu Nành Vinamilk        1432.0           596.0     2028.0
7      Sữa đậu nành Nutifood        1896.0             0.0     1896.0
8         TH True Light Meal         884.0            19.0      903.0
9   Vinamilk Sữa hạt Cao Đạm         617.0            22.0      639.0
10               TH true OAT         270.0             0.0      270.0
11             Nunut Lục Bảo         129.0             0.0      129.0
12      Sữa đậu nành Vinasoy          48.0             0.0       48.0
13             Sản phẩm khác          37.0             0.0       37.0

==================================================

In [36]:
#Sentiment BDD

filtered_sh_sentiment_BDD = sh_sentiment[(sh_sentiment["Ngành hàng"].isin(bdd)) & (sh_sentiment["Thời gian"].str.contains(year, na=False))]
sentiment_BDD = filtered_sh_sentiment_BDD.groupby(["Sản phẩm"]).agg(sentiment_columns).sort_values(by="Total new", ascending=False).reset_index().round()
sentiment_BDD["Khác"] = sentiment_BDD["Total new"] - sentiment_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

sentiment_BDD_top_13 = sentiment_BDD.head(13)

SP_khac = sentiment_BDD.iloc[13:].agg(sentiment_columns).to_frame().transpose()
    
sentiment_BDD = pd.concat([sentiment_BDD_top_13, SP_khac], ignore_index=True)
sentiment_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
sentiment_BDD.loc[13, 'Khác'] = sentiment_BDD.loc[13, 'Total new']
sentiment_BDD

,Sản phẩm,Total new,Positive new,Neutral new,Negative new,Khác
0,Gerber,10665.0,300.0,10365.0,0.0,0.0
1,Bột ăn dặm Hipp,9141.0,861.0,8265.0,15.0,0.0
2,Vinamilk Ridielac,7583.0,2375.0,5205.0,3.0,0.0
3,Bột ăn dặm Nuti IQ,985.0,330.0,655.0,0.0,0.0
4,Bột Dinh Dưỡng Vinamilk,639.0,127.0,512.0,0.0,0.0
5,Bột ăn dặm Metacare,218.0,33.0,185.0,0.0,0.0
6,Cerelac,135.0,27.0,108.0,0.0,0.0
7,Bột ăn dặm Vinamilk Optimum Gold,94.0,2.0,92.0,0.0,0.0
8,Bột ăn dặm Coloscare,7.0,0.0,7.0,0.0,0.0
9,Bột ăn dặm Vinamilk Organic Gold,1.0,0.0,1.0,0.0,0.0
10,NaN,0.0,0.0,0.0,0.0,NaN
13,Sản phẩm khác,NaN,NaN,NaN,NaN,NaN

In [37]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    sentiment_BDD.to_excel(writer, index=False, sheet_name='Sentiment BDD')

In [38]:
#Relevant BDD

filtered_sh_relevant_BDD = sh_relevant[(sh_relevant["Ngành hàng"].isin(bdd)) & (sh_relevant["Thời gian"].str.contains(year, na=False))]
relevant_BDD = filtered_sh_relevant_BDD.groupby(["Sản phẩm"]).agg(relevant_columns).sort_values(by="Total new", ascending=False).reset_index().round()
relevant_BDD["Khác"] = relevant_BDD["Total new"] - relevant_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

relevant_BDD_top_13 = relevant_BDD.head(13)

SP_khac = relevant_BDD.iloc[13:].agg(relevant_columns).to_frame().transpose()
    
relevant_BDD = pd.concat([relevant_BDD_top_13, SP_khac], ignore_index=True)
relevant_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
relevant_BDD.loc[13, 'Khác'] = relevant_BDD.loc[13, 'Total new']
relevant_BDD

,Sản phẩm,Relevant new,Irrelevant new,Total new,Khác
0,Gerber,10665.0,0.0,10665.0,0.0
1,Bột ăn dặm Hipp,8856.0,285.0,9141.0,0.0
2,Vinamilk Ridielac,7326.0,257.0,7583.0,0.0
3,Bột ăn dặm Nuti IQ,985.0,0.0,985.0,0.0
4,Bột Dinh Dưỡng Vinamilk,639.0,0.0,639.0,0.0
5,Bột ăn dặm Metacare,217.0,1.0,218.0,0.0
6,Cerelac,135.0,0.0,135.0,0.0
7,Bột ăn dặm Vinamilk Optimum Gold,94.0,0.0,94.0,0.0
8,Bột ăn dặm Coloscare,7.0,0.0,7.0,0.0
9,Bột ăn dặm Vinamilk Organic Gold,1.0,0.0,1.0,0.0
10,NaN,0.0,0.0,0.0,NaN
13,Sản phẩm khác,NaN,NaN,NaN,NaN

In [39]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    relevant_BDD.to_excel(writer, index=False, sheet_name='Relevant BDD')

Channel

In [40]:
def process_data_channel(df, columns, nganh_hang, year):
    filtered_df = df[(df["Ngành hàng"] == nganh_hang) & (df["Thời gian"].str.contains(year, na=False))]
    
    grouped_df = filtered_df.groupby(["Sản phẩm"]).agg(columns).sort_values(by="Total new", ascending=False).reset_index().round()
    
    grouped_df['Khác'] = grouped_df["Total new"] - grouped_df.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)
    
    top_13 = grouped_df.head(13)
    khac = grouped_df.iloc[13:].agg(columns).to_frame().transpose()
    
    result_df = pd.concat([top_13, khac], ignore_index=True)
    result_df.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
    result_df.loc[13, 'Khác'] = result_df.loc[13, 'Total new'] - result_df.loc[13, ['Fanpage new', 'FB page new', 'FB user new', 'FB group new', 'Tiktok new', 'Forum new', 'News new', 'Youtube new']].sum()
    result_df = result_df[['Sản phẩm','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
    
    return result_df

# Define columns for Channel
channel_columns = {"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx"
existing_excel = pd.ExcelFile(existing_excel_path)

with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    start_column = 0  # Initialize start column for each df
    for nganh_hang in nganh_hang_list:
        # Process data for each nganh_hang
        channel_data = process_data(sh_channel, channel_columns, nganh_hang, year)
        
        # Rename the 'Sản phẩm' column to the current 'nganh_hang' value
        channel_data.rename(columns={'Sản phẩm': nganh_hang}, inplace=True)
        
        # Display the sentiment_data for debugging
        print(f"Channel ({nganh_hang}):")
        print(channel_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        channel_data.to_excel(writer, sheet_name="Channel_Cate", startcol=start_column, index=False)
        
        # Adjust start column for the next DataFrame
        start_column += len(channel_data.columns) + 3  # Increment by number of columns + some padding

# Close the existing Excel file
existing_excel.close()

Channel (SC):
                           SC  Fanpage new  FB page new  FB user new  \
0           Sữa chua Vinamilk      72986.0     223562.0     490677.0
1              Vinamilk Probi      11604.0     424813.0     254397.0
2               Vinamilk Susu     188729.0     150829.0     267910.0
3               Vinamilk Hero     187211.0     150422.0     265698.0
4                      Yomost      10669.0     101746.0      29970.0
5             Sữa chua Yakult      11184.0      22252.0      18856.0
6              TH True Yogurt       8020.0      13858.0       6111.0
7               Sữa chua Hoff         48.0       7358.0      14528.0
8                        Veyo       5754.0         55.0       2244.0
9             Sữa chua TOPKID       1061.0       2545.0       1802.0
10          Sữa chua ăn Ba Vì        100.0        518.0       3547.0
11      Sữa chua uống LIF KUN         19.0        478.0       2647.0
12  Sữa chua uống Nestle Yogu          3.0        400.0       3572.0
13              Sản phẩm khác       2647.0       3795.0       9928.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0        49185.0     14501.0       13.0      21.0        121.0   851274.0
1        22040.0     23768.0       27.0       2.0        523.0   737479.0
2         1988.0     45079.0        0.0       7.0       5374.0   659916.0
3          674.0     44915.0        0.0       7.0       5181.0   654108.0
4        19713.0     29314.0        2.0      12.0         76.0   191505.0
5         3100.0      8480.0       88.0      49.0        151.0    64187.0
6         4743.0       567.0       20.0     169.0        116.0    33612.0
7         5114.0      3290.0        2.0       0.0          4.0    30349.0
8          289.0        16.0        0.0      51.0          4.0     8413.0
9         2158.0         8.0        0.0       0.0         26.0     7602.0
10        1679.0        13.0       10.0      27.0          5.0     5905.0
11        1661.0       127.0        1.0       1.0        804.0     5739.0
12         830.0         4.0        0.0       0.0          0.0     4809.0
13        9064.0      1044.0       20.0      66.0        281.0    26880.0

==================================================

Channel (SN):
                           SN  Fanpage new  FB page new  FB user new  \
0                        Milo       8259.0     758574.0     956255.0
1                     LOF KUN     150556.0      76927.0     429336.0
2               Vinamilk 100%       3670.0      46891.0     210902.0
3      Sữa lúa mạch Lof Malto      22983.0       8655.0       7240.0
4         Vinamilk Green Farm        354.0      31126.0      22406.0
5       Sữa tươi TH True Milk       4492.0       4415.0       5926.0
6   Sữa tươi Dutch Lady (RTD)       4814.0       3801.0       8349.0
7                    Ovaltine      12795.0       1107.0       6337.0
8        Sữa tươi Đà Lạt Milk        240.0       4755.0       6281.0
9               Vinamilk Fino       7440.0        686.0       5596.0
10            Sữa nước Nestlé          7.0       3057.0      10081.0
11          Sữa trái cây Oggi         69.0      10312.0       3854.0
12   Sữa non Colos Fresh Milk       6398.0       1091.0       7201.0
13              Sản phẩm khác      23921.0      18297.0      34530.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0        93384.0     11393.0       48.0     458.0         78.0  1828459.0
1        30242.0    278374.0       81.0     277.0       6520.0   973214.0
2        16409.0      5563.0        0.0       0.0         47.0   283488.0
3         1263.0     19810.0        0.0      25.0       1057.0    61035.0
4         1411.0      4929.0        3.0     149.0        227.0    60680.0
5        26865.0      1620.0      177.0     245.0        165.0    43940.0
6        20033.0       852.0       14.0      36.0         44.0    37952.0
7          997.0      1073.0       21.0       5.0         24.0    22360.0
8         9235.0       495.0        9.0      24.0         41.0    21192.0
9         4472.0      2454.0        0.0       0.0          7.0    20657.0
10        4231.0       219.0        0.0      13.0          6.0    17614.0
11        1229.0       169.0        0.0       2.0         15.0    15650.0
12         549.0        11.0        0.0       0.0          0.0    15257.0
13       34565.0     12854.0       77.0     280.0        350.0   125046.0

==================================================

Channel (SB):
                           SB  Fanpage new  FB page new  FB user new  \
0                   Nuvi Grow    1767343.0      25232.0      44305.0
1                   Grow Plus     148081.0     131371.0     419488.0
2   Vinamilk Dielac Grow Plus       4912.0      18320.0     717564.0
3                  Colos gain      10271.0     293986.0     293931.0
4               Nan Optipro 4      22083.0     282387.0     220177.0
5         Abbott Grow Vietnam     362034.0      14916.0     129295.0
6          Vinamilk Yoko Gold       2089.0      38259.0     309217.0
7               S-26 Ultima 3     151129.0     163057.0      23175.0
8             Similac Vietnam       4526.0     167938.0      12960.0
9           Pediasure Vietnam      11633.0      43059.0     213461.0
10                        Nan      19225.0      24546.0      39797.0
11           Vinamilk Optimum       7385.0      17872.0     152051.0
12      Vinamilk Sure Prevent       5050.0      43203.0     122217.0
13              Sản phẩm khác     136883.0     483472.0     616337.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0        12014.0      3016.0        0.0      20.0        120.0  1852078.0
1       158655.0     21325.0       16.0     104.0        240.0   880980.0
2        35354.0      8109.0        1.0       1.0         33.0   784300.0
3       102918.0      5295.0        0.0       0.0         39.0   706580.0
4        87195.0        85.0        3.0       3.0          4.0   611943.0
5        18208.0     11253.0        7.0      22.0          2.0   535736.0
6        55200.0       940.0        6.0       3.0          3.0   405780.0
7        27191.0      2979.0        1.0       0.0          5.0   367538.0
8       156059.0      5887.0       82.0      19.0         89.0   347562.0
9        33511.0      1227.0       65.0      34.0         20.0   303012.0
10      204444.0      2899.0       20.0       3.0          6.0   291004.0
11       62932.0      5611.0       20.0       1.0         29.0   245908.0
12       12674.0     33831.0        1.0     198.0        299.0   217474.0
13      344883.0     44252.0      397.0     887.0        739.0  1629281.0

==================================================

Channel (SĐ):
                              SĐ  Fanpage new  FB page new  FB user new  \
0               Vinamilk Ông thọ       1598.0      96189.0     193609.0
1   Vinamilk Ngôi Sao Phương Nam         19.0       5405.0       3870.0
2             Sữa đặc Dutch Lady          0.0        708.0       3647.0
3               Sữa đặc Vinamilk          0.0        185.0       2074.0
4               Vinamilk Tài lộc          0.0         88.0       1527.0
5               Sữa đặc Nutifood          0.0        204.0        276.0
6               Sữa đặc Hoàn Hảo          0.0          3.0         13.0
7                            NaN          0.0          0.0          0.0
13                 Sản phẩm khác          NaN          NaN          NaN

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0       135138.0      6309.0      100.0     549.0       1705.0   435398.0
1         7273.0       635.0       10.0      91.0         18.0    17338.0
2         2946.0         5.0        3.0       6.0          2.0     7317.0
3         4687.0         6.0        1.0      82.0         15.0     7050.0
4         1629.0        41.0        0.0       0.0          2.0     3289.0
5          571.0         4.0        0.0       4.0          0.0     1060.0
6          213.0         0.0        0.0       0.0          0.0      229.0
7            0.0         0.0        0.0       0.0          0.0        0.0
13           NaN         NaN        NaN       NaN          NaN        NaN

==================================================

Channel (SĐN):
                         SĐN  Fanpage new  FB page new  FB user new  \
0                       Fami      91677.0      19212.0      30615.0
1                TH True Nut       2708.0       3873.0      14771.0
2         Vinamilk Super Nut        185.0        520.0       2019.0
3        Vinamilk Hạt Óc Chó       2566.0       1398.0        623.0
4         Vinamilk Hạnh Nhân       2605.0         49.0        144.0
5            Vinamilk Đậu Đỏ       2605.0         49.0        128.0
6      Sữa Đậu Nành Vinamilk       1619.0         45.0        239.0
7      Sữa đậu nành Nutifood          0.0         49.0       1306.0
8         TH True Light Meal        494.0        168.0         88.0
9   Vinamilk Sữa hạt Cao Đạm         88.0        126.0        290.0
10               TH true OAT         18.0        182.0         33.0
11             Nunut Lục Bảo          0.0         19.0         99.0
12      Sữa đậu nành Vinasoy          1.0          5.0         31.0
13             Sản phẩm khác          0.0          4.0         26.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0        14187.0      2693.0       12.0     115.0        231.0   158760.0
1         3317.0       122.0       14.0      51.0         39.0    24901.0
2         1260.0       690.0        0.0      39.0          4.0     4855.0
3          189.0         2.0        2.0       0.0          4.0     4789.0
4           41.0         0.0        0.0       0.0          0.0     2842.0
5           36.0         0.0        0.0       0.0          0.0     2823.0
6          113.0         0.0        1.0       1.0          1.0     2028.0
7          529.0         9.0        0.0       1.0          2.0     1896.0
8           80.0         7.0        0.0      23.0         43.0      903.0
9           68.0        64.0        0.0       0.0          0.0      639.0
10          31.0         0.0        0.0       3.0          0.0      270.0
11          11.0         0.0        0.0       0.0          0.0      129.0
12           7.0         0.0        0.0       4.0          0.0       48.0
13           1.0         1.0        0.0       0.0          3.0       37.0

==================================================

In [41]:
# Channel BDD
filtered_sh_channel_BDD = sh_channel[(sh_channel["Ngành hàng"].isin(bdd)) & (sh_channel["Thời gian"].str.contains(year, na=False))]
channel_BDD = filtered_sh_channel_BDD.groupby(["Sản phẩm"]).agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()  
channel_BDD["Khác"] = channel_BDD["Total new"] - channel_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

channel_BDD_top_13 = channel_BDD.head(13)

SP_khac = channel_BDD.iloc[13:].agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).to_frame().transpose()
    
channel_BDD = pd.concat([channel_BDD_top_13, SP_khac], ignore_index=True)
channel_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
channel_BDD.loc[13, 'Khác'] = channel_BDD.loc[13, 'Total new'] - channel_BDD.loc[13, ['Fanpage new', 'FB page new', 'FB user new', 'FB group new', 'Tiktok new', 'Forum new', 'News new', 'Youtube new']].sum()
channel_BDD = channel_BDD[['Sản phẩm','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
channel_BDD

,Sản phẩm,Fanpage new,FB page new,FB user new,FB group new,Tiktok new,Forum new,News new,Youtube new,Khác,Total new
0,Gerber,35.0,5745.0,3771.0,1076.0,32.0,1.0,0.0,4.0,1.0,10665.0
1,Bột ăn dặm Hipp,34.0,2666.0,2940.0,3111.0,319.0,0.0,0.0,2.0,69.0,9141.0
2,Vinamilk Ridielac,3222.0,1336.0,2010.0,817.0,188.0,0.0,4.0,5.0,1.0,7583.0
3,Bột ăn dặm Nuti IQ,1.0,387.0,219.0,372.0,6.0,0.0,0.0,0.0,0.0,985.0
4,Bột Dinh Dưỡng Vinamilk,1.0,118.0,246.0,169.0,7.0,0.0,97.0,1.0,0.0,639.0
5,Bột ăn dặm Metacare,67.0,66.0,61.0,16.0,8.0,0.0,0.0,0.0,0.0,218.0
6,Cerelac,0.0,30.0,64.0,31.0,1.0,0.0,0.0,1.0,8.0,135.0
7,Bột ăn dặm Vinamilk Optimum Gold,1.0,4.0,13.0,75.0,0.0,0.0,1.0,0.0,0.0,94.0
8,Bột ăn dặm Coloscare,0.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
9,Bột ăn dặm Vinamilk Organic Gold,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
13,Sản phẩm khác,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    channel_BDD.to_excel(writer, index=False, sheet_name='Channel BDD')