In [1]:
import pandas as pd
import re

In [2]:
sh_sentiment = pd.read_excel(r"D:\\Data Kompa\Vinamilk\Tính 17.12.2024.xlsx", sheet_name='Sentiment')
sh_relevant = pd.read_excel(r"D:\\Data Kompa\Vinamilk\Tính 17.12.2024.xlsx", sheet_name='Relevant')
sh_channel = pd.read_excel(r"D:\\Data Kompa\Vinamilk\Tính 17.12.2024.xlsx", sheet_name='Channel')

# Phân tích biến

Sheet Sentiment

In [3]:
sh_sentiment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20788 entries, 0 to 20787
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Thương hiệu       20788 non-null  object
 1   Ngành hàng        20788 non-null  object
 2   Sản phẩm          20788 non-null  object
 3   Thời gian         20788 non-null  datetime64[ns]
 4   Tuần              20788 non-null  object
 5   Positive          13751 non-null  float64
 6   Neutral           20429 non-null  float64
 7   Negative          6162 non-null   float64
 8   Blank             7790 non-null   float64
 9   Total after       20788 non-null  float64
 10  Blank.1           20787 non-null  float64
 11  Total             20788 non-null  float64
 12  Buzzes thêm       345 non-null    float64
 13  Sum of comments   16730 non-null  float64
 14  Sum of shares     16730 non-null  float64
 15  Positive new      20704 non-null  float64
 16  Neutral new       20788 non-null  float64
 17  Negative new      20574 non-null  float64
 18  Total new         20788 non-null  float64
 19  Check Total Buzz  20788 non-null  int64
 20  Ghi chú           522 non-null    object
 21  Số campaign       206 non-null    object
 22  Phân loại         20788 non-null  object
dtypes: datetime64[ns](1), float64(14), int64(1), object(7)
memory usage: 3.6+ MB

In [4]:
object_columns = list(sh_sentiment.select_dtypes(['object']).columns)
object_columns

['Thương hiệu',
 'Ngành hàng',
 'Sản phẩm',
 'Tuần',
 'Ghi chú',
 'Số campaign',
 'Phân loại']

In [5]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_sentiment[column].unique()), "unique values", "\t & \t", 
          sh_sentiment[column].notnull().sum(), "non-null values\t", 
          round(100* sh_sentiment[column].notnull().sum()/len(sh_sentiment[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 20788 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 20788 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
276 unique values 	 & 	 20788 non-null values	 100.0 % non-null
*, Column:  Tuần
114 unique values 	 & 	 20788 non-null values	 100.0 % non-null
*, Column:  Ghi chú
310 unique values 	 & 	 522 non-null values	 2.51 % non-null
*, Column:  Số campaign
110 unique values 	 & 	 206 non-null values	 0.99 % non-null
*, Column:  Phân loại
17 unique values 	 & 	 20788 non-null values	 100.0 % non-null

In [6]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_sentiment[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        5383
TH True Milk    2303
Nutifood        2149
Nutricare       2056
Vitadairy       1795
Nestlé          1519
FCV             1034
IDP              943
Mead Johnson     834
Abbott           684
Vinasoy          412
Đà Lạt Milk      383
Hipp             342
Fonterra         318
Betagen          243
Yakult           228
Hoff             162
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       7741
SN       3689
SC       2793
BRAND    1720
NGK      1214
SĐN      1214
SĐ        696
KEM       665
BAD       409
BDD       227
BƠ        108
ĐƯỜNG     101
PM         92
FOOD       79
Brand      30
TUNL       10
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
ColosBaby                 118
Vinamilk 100%             116
EnfaGrow Premium          114
Nan Infinipro A2          114
Vinamilk Fino             114
                         ...
Leanmax Colostrum           1
Vinamilk Platinum           1
Vinamilk Probeauty          1
Vinamilk Greek Yoghurt      1
Vinamilk Kefir              1
Name: Sản phẩm, Length: 276, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Tuần
01/09/2024 - 07/09/2024    219
15/09/2024 - 21/09/2024    218
08/09/2024 - 14/09/2024    216
01/10/2024 - 07/10/2024    216
08/06/2024 - 14/06/2024    215
                          ...
29/03/2023 - 31/03/2023    123
29/01/2023 - 31/01/2023    120
29/05/2023 - 31/05/2023    118
22/01/2023 - 28/01/2023    114
29/04/2023 - 30/04/2023    111
Name: Tuần, Length: 114, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
rao vặt                                                                                                                          59
minigame trên fanpage                                                                                                            14
Abbott Grow - Dinh Dưỡng Hàng Đầu, Mùa Hè Vui Số 1                                                                                8
không lấy shares ảo                                                                                                               7
rao vặt sản phẩm                                                                                                                  6
                                                                                                                                 ..
rao vặt, negative từ post tiktok https://www.tiktok.com/@cocacana/video/7286360842604399890                                       1
Cùng Kun Vận Động và các video tiktok phim hoạt hình ngắn "Thợ săn thành phố". Còn lại là các bài rao vặt                         1
MINIGAME: BẮT KHOẢNH KHẮC "SIÊU NGON" CÙNG SỮA TƯƠI CỐM NON trên fanpage  http://facebook.com/101771025269874_641219041460528     1
EnfaMil A+ Em Bé Nhỏ Làm Điều To To                                                                                               1
Campaign Dielac Grow Plus - Ngày Hội Dinh Dưỡng                                                                                   1
Name: Ghi chú, Length: 309, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Số campaign
5000                                                                   19
1000                                                                    9
3000                                                                    9
10000                                                                   7
800                                                                     6
                                                                       ..
1500: #MILOBich #MILOBichTietKiem #MILO #MILOVietNam                    1
1000: #NANSupremePro3 #nguanguycodiung #Tangdekhang #danggoitienloi     1
2500: #NutrenJunior #TangTruong3Chuan #NestléHealthScience              1
#NestleS26Ultima3 #ChonDinhDuongKhoaHoc #TangTocDoKetNoiNaoBo           1
600                                                                     1
Name: Số campaign, Length: 109, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Phân loại
SBTE     5319
SN       3689
SBNL     2422
BRAND    1750
SCU      1685
SĐN      1214
NGK      1214
SCA      1108
SĐ        696
KEM       665
BAD       409
BDD       227
BƠ        108
ĐƯỜNG     101
PM         92
FOOD       79
TUNL       10
Name: Phân loại, dtype: int64
----------------------------------------------------------------------------------------------------

Sheet Relevant

In [7]:
sh_relevant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4727 entries, 0 to 4726
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Thương hiệu       4727 non-null   object
 1   Ngành hàng        4727 non-null   object
 2   Sản phẩm          4727 non-null   object
 3   Thời gian         4727 non-null   datetime64[ns]
 4   Relevant          4718 non-null   float64
 5   Irrelevant        2740 non-null   float64
 6   Blank             1844 non-null   float64
 7   Total after       4727 non-null   int64
 8   Total             4727 non-null   float64
 9   Buzzes thêm       211 non-null    float64
 10  Relevant new      4727 non-null   float64
 11  Irrelevant new    4727 non-null   float64
 12  Total new         4727 non-null   float64
 13  Check Total Buzz  4727 non-null   int64
 14  Ghi chú           4 non-null      object
dtypes: datetime64[ns](1), float64(8), int64(2), object(4)
memory usage: 554.1+ KB

In [8]:
object_columns = list(sh_relevant.select_dtypes(['object']).columns)
object_columns

['Thương hiệu', 'Ngành hàng', 'Sản phẩm', 'Ghi chú']

In [9]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_relevant[column].unique()), "unique values", "\t & \t", 
          sh_relevant[column].notnull().sum(), "non-null values\t", 
          round(100* sh_relevant[column].notnull().sum()/len(sh_relevant[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 4727 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 4727 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
277 unique values 	 & 	 4727 non-null values	 100.0 % non-null
*, Column:  Ghi chú
5 unique values 	 & 	 4 non-null values	 0.08 % non-null

In [10]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_relevant[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        1219
Nutricare        566
Nutifood         516
TH True Milk     492
Vitadairy        385
Nestlé           343
FCV              232
IDP              208
Mead Johnson     183
Abbott           138
Vinasoy           89
Đà Lạt Milk       82
Hipp              69
Fonterra          68
Betagen           57
Yakult            46
Hoff              34
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       1827
SN        791
SC        605
BRAND     369
NGK       294
SĐN       277
SĐ        156
KEM       140
BAD        98
BDD        58
ĐƯỜNG      29
BƠ         23
PM         21
FOOD       17
Kem        12
TUNL       10
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
Vinamilk Susu                   24
ColosBaby                       24
Thương hiệu Abbott              23
Nan Optipro 4                   23
Vinamilk Ngôi Sao Phương Nam    23
                                ..
Nuvi Rau củ                      1
Leanmax Colostrum                1
Vinamilk Probeauty               1
Vinamilk Super Susu              1
Nunest Kid                       1
Name: Sản phẩm, Length: 277, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
yes, minigame, fanpage                1
#DinhDuongChatLuong #ViConLaSo1       1
#VềNhàĐónVuLan và  #VuiSongMoiNgay    1
campaign Bé Lành Học Nhanh            1
Name: Ghi chú, dtype: int64
----------------------------------------------------------------------------------------------------

Sheet Channel

In [11]:
sh_channel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4726 entries, 0 to 4725
Data columns (total 36 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Thương hiệu                   4726 non-null   object
 1   Ngành hàng                    4726 non-null   object
 2   Sản phẩm                      4726 non-null   object
 3   Thời gian                     4726 non-null   datetime64[ns]
 4   Fanpage                       2767 non-null   float64
 5   FB page                       4110 non-null   float64
 6   FB user                       4213 non-null   float64
 7   FB group                      4102 non-null   float64
 8   Tiktok                        2584 non-null   float64
 9   Forum                         928 non-null    float64
 10  News                          1469 non-null   float64
 11  Youtube                       1305 non-null   float64
 12  E-commerce                    333 non-null    float64
 13  Instagram                     158 non-null    float64
 14  Threads                       554 non-null    float64
 15  Linkedin                      96 non-null     float64
 16  Total after                   4726 non-null   int64
 17  Total                         4726 non-null   float64
 18  Total FB và Total FB, Tiktok  4726 non-null   float64
 19  Buzzes thêm                   297 non-null    float64
 20  Fanpage new                   4700 non-null   float64
 21  FB page new                   4700 non-null   float64
 22  FB user new                   4700 non-null   float64
 23  FB group new                  4700 non-null   float64
 24  Tiktok new                    4722 non-null   float64
 25  Forum new                     4726 non-null   int64
 26  News new                      4726 non-null   int64
 27  Youtube new                   4726 non-null   int64
 28  E-commerce new                4726 non-null   int64
 29  Instagram new                 4726 non-null   int64
 30  Threads new                   4726 non-null   int64
 31  Linkedin new                  4726 non-null   int64
 32  Total new                     4726 non-null   float64
 33  Check Total Buzz              4726 non-null   int64
 34  Total Facebook                4726 non-null   float64
 35  Ghi chú                       5 non-null      object
dtypes: datetime64[ns](1), float64(22), int64(9), object(4)
memory usage: 1.3+ MB

In [12]:
object_columns = list(sh_channel.select_dtypes(['object']).columns)
object_columns

['Thương hiệu', 'Ngành hàng', 'Sản phẩm', 'Ghi chú']

In [13]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_channel[column].unique()), "unique values", "\t & \t", 
          sh_channel[column].notnull().sum(), "non-null values\t", 
          round(100* sh_channel[column].notnull().sum()/len(sh_channel[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 4726 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 4726 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
276 unique values 	 & 	 4726 non-null values	 100.0 % non-null
*, Column:  Ghi chú
6 unique values 	 & 	 5 non-null values	 0.11 % non-null

In [14]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_sentiment[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        5383
TH True Milk    2303
Nutifood        2149
Nutricare       2056
Vitadairy       1795
Nestlé          1519
FCV             1034
IDP              943
Mead Johnson     834
Abbott           684
Vinasoy          412
Đà Lạt Milk      383
Hipp             342
Fonterra         318
Betagen          243
Yakult           228
Hoff             162
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       7741
SN       3689
SC       2793
BRAND    1720
NGK      1214
SĐN      1214
SĐ        696
KEM       665
BAD       409
BDD       227
BƠ        108
ĐƯỜNG     101
PM         92
FOOD       79
Brand      30
TUNL       10
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
ColosBaby                 118
Vinamilk 100%             116
EnfaGrow Premium          114
Nan Infinipro A2          114
Vinamilk Fino             114
                         ...
Leanmax Colostrum           1
Vinamilk Platinum           1
Vinamilk Probeauty          1
Vinamilk Greek Yoghurt      1
Vinamilk Kefir              1
Name: Sản phẩm, Length: 276, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
rao vặt                                                                                                                          59
minigame trên fanpage                                                                                                            14
Abbott Grow - Dinh Dưỡng Hàng Đầu, Mùa Hè Vui Số 1                                                                                8
không lấy shares ảo                                                                                                               7
rao vặt sản phẩm                                                                                                                  6
                                                                                                                                 ..
rao vặt, negative từ post tiktok https://www.tiktok.com/@cocacana/video/7286360842604399890                                       1
Cùng Kun Vận Động và các video tiktok phim hoạt hình ngắn "Thợ săn thành phố". Còn lại là các bài rao vặt                         1
MINIGAME: BẮT KHOẢNH KHẮC "SIÊU NGON" CÙNG SỮA TƯƠI CỐM NON trên fanpage  http://facebook.com/101771025269874_641219041460528     1
EnfaMil A+ Em Bé Nhỏ Làm Điều To To                                                                                               1
Campaign Dielac Grow Plus - Ngày Hội Dinh Dưỡng                                                                                   1
Name: Ghi chú, Length: 309, dtype: int64
----------------------------------------------------------------------------------------------------

# Tổng quan

In [15]:
Link = r"D:\\Data Kompa\Vinamilk\\Nov2024.xlsx"
month = "11/2024"
year = "2024"

pre_month = '10/2023'
pre_ytd = ['01/2023','02/2023','03/2023','04/2023','05/2023','06/2023','07/2023','08/2023','09/2023','10/2023','11/2023']
pre_year = "2023"

In [16]:
exclude_brands = ["Hoff", "Betagen", "Yakult"]
bdd = ['BAD', 'BDD']

In [17]:
#Thị phần ngành sữa theo Tháng năm 2024
#filtered_sh_sentiment_mon = sh_sentiment[(sh_sentiment["Thời gian"] == month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
#SOV = filtered_sh_sentiment_mon.groupby(["Thương hiệu"]).agg({"Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
#SOV.columns=['month','Total new']
#SOV

In [18]:
#with pd.ExcelWriter(Link, engine='openpyxl') as writer:
    #SOV.to_excel(writer, sheet_name='month_brand', startrow=0, startcol=0, index=False)

In [19]:
#Thị phần ngành sữa theo Tháng năm 2023
filtered_sh_sentiment_pre_ytd = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV_pre_YTD = filtered_sh_sentiment_pre_ytd.pivot_table(index='Thương hiệu',columns ='Thời gian', values ='Total new', aggfunc = sum).round().reset_index()
SOV_pre_YTD['Total'] = SOV_pre_YTD.sum(axis=1)
SOV_pre_YTD = SOV_pre_YTD.sort_values(by='Total',ascending=False)
SOV_pre_YTD.columns = ['Thương hiệu']+ pre_ytd +['Total']
SOV_pre_YTD

C:\Users\Kompa-KTelt056\AppData\Local\Temp\ipykernel_1444\2624929670.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  SOV_pre_YTD['Total'] = SOV_pre_YTD.sum(axis=1)

,Thương hiệu,01/2023,02/2023,03/2023,04/2023,05/2023,06/2023,07/2023,08/2023,09/2023,10/2023,11/2023,Total
10,Vinamilk,289858.0,224810.0,102235.0,133340.0,671185.0,351706.0,518277.0,309037.0,887925.0,1180629.0,697433.0,5366435.0
6,Nestlé,70138.0,230100.0,46971.0,30714.0,48188.0,322594.0,444269.0,1148122.0,65469.0,1698206.0,382173.0,4486944.0
1,FCV,102689.0,58495.0,47644.0,69171.0,74412.0,24991.0,125129.0,313573.0,673093.0,159391.0,109647.0,1758235.0
0,Abbott,272404.0,44927.0,31062.0,36060.0,138229.0,79531.0,47307.0,84220.0,162129.0,75476.0,162452.0,1133797.0
7,Nutifood,20403.0,27266.0,165974.0,56727.0,44913.0,84670.0,73964.0,118327.0,90868.0,66110.0,99278.0,848500.0
9,TH True Milk,5234.0,16824.0,11378.0,26615.0,14339.0,26190.0,29923.0,83559.0,33522.0,47313.0,30231.0,325128.0
4,IDP,19267.0,24189.0,7663.0,20189.0,22116.0,23784.0,24313.0,77729.0,24185.0,42053.0,29812.0,315300.0
5,Mead Johnson,8871.0,13308.0,15741.0,33959.0,18194.0,30593.0,20759.0,36564.0,41126.0,24601.0,21446.0,265162.0
11,Vinasoy,9591.0,26456.0,9693.0,35135.0,3620.0,6661.0,11491.0,87843.0,23111.0,27271.0,14801.0,255673.0
12,Vitadairy,4334.0,12062.0,13927.0,5742.0,5413.0,22449.0,25734.0,32911.0,32207.0,34034.0,51152.0,239965.0
2,Fonterra,1703.0,449.0,1127.0,947.0,547.0,3184.0,4679.0,9078.0,2070.0,3804.0,81960.0,109548.0
8,Nutricare,NaN,NaN,NaN,NaN,NaN,NaN,7656.0,10606.0,13733.0,17991.0,22234.0,72220.0
13,Đà Lạt Milk,143.0,286.0,241.0,1489.0,243.0,512.0,684.0,9460.0,1411.0,3704.0,3644.0,21817.0
3,Hipp,726.0,405.0,732.0,803.0,789.0,727.0,1659.0,2518.0,1984.0,4589.0,4411.0,19343.0

In [20]:
#Sentiment các brand theo Tháng năm 2024
filtered_sh_sentiment_mon = sh_sentiment[(sh_sentiment["Thời gian"] == month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
brand_sent = filtered_sh_sentiment_mon.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
brand_sent.columns=['month','Positive','Neutral','Negative','Total new']
brand_sent

           month  Positive   Neutral  Negative  Total new
0         Nestlé  592550.0   33425.0      20.0   625995.0
1      Vitadairy  451154.0   89257.0      14.0   540425.0
2       Vinamilk  228788.0  157040.0     290.0   386118.0
3       Nutifood   40195.0   65067.0      77.0   105339.0
4         Abbott   36227.0   41065.0     262.0    77554.0
5            IDP   16895.0   32007.0     470.0    49371.0
6   TH True Milk   10660.0   25176.0      61.0    35897.0
7            FCV    9489.0   24696.0      39.0    34224.0
8   Mead Johnson   19687.0    8556.0     362.0    28606.0
9           Hipp   13179.0    6999.0      10.0    20188.0
10     Nutricare     828.0   16102.0       6.0    16936.0
11      Fonterra   14063.0    1877.0       2.0    15942.0
12       Vinasoy    1791.0    4760.0      18.0     6569.0
13   Đà Lạt Milk     236.0    3907.0       1.0     4144.0

In [21]:
#with pd.ExcelWriter(Link, engine='openpyxl',mode='a') as writer:
    #brand_sent.to_excel(writer, index=False, sheet_name='month_brand_sent')

In [22]:
#Sắc thái thảo luận của các thương hiệu pre-YTD
filtered_sh_sentiment_pre_ytd = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
brand_sent_pre_ytd = filtered_sh_sentiment_pre_ytd.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
brand_sent_pre_ytd.columns =['preYTD','Positive','Neutral','Negative','Total new']
brand_sent_pre_ytd

          preYTD   Positive   Neutral  Negative  Total new
0       Vinamilk  4497609.0  865187.0    3639.0  5366435.0
1         Nestlé  3810089.0  676094.0     761.0  4486944.0
2            FCV  1219053.0  538119.0    1062.0  1758235.0
3         Abbott   607257.0  522341.0    4198.0  1133797.0
4       Nutifood   684614.0  163345.0     541.0   848500.0
5   TH True Milk    68738.0  253792.0    2597.0   325128.0
6            IDP   115991.0  198326.0     983.0   315300.0
7   Mead Johnson   190254.0   74285.0     623.0   265162.0
8        Vinasoy   119800.0  131957.0    3916.0   255673.0
9      Vitadairy   101859.0  137164.0     942.0   239965.0
10      Fonterra    44282.0   65245.0      21.0   109548.0
11     Nutricare    10884.0   61185.0     152.0    72220.0
12   Đà Lạt Milk     1642.0   20157.0      18.0    21817.0
13          Hipp     4857.0   14371.0     115.0    19343.0

In [23]:
#Category_pre-YTD
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands))]
cate = filtered_sh_sentiment.pivot_table(index='Thương hiệu', columns='Ngành hàng', values='Total new', aggfunc='sum').round(decimals=0).fillna(0)
cate['Total'] = cate.sum(axis=1)
cate = cate.sort_values(by="Total",ascending=False)
cate.reset_index(inplace=True)
cate['BDD'] = cate[['BDD','BAD']].sum(axis=1)
cate['Khác'] = cate['Total'] - cate[['SN','SC','SB','BDD','SĐ','SĐN']].sum(axis=1)
cate = cate[['Thương hiệu','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']]
cate.columns = ['pre_YTD','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']
cate

,pre_YTD,SN,SC,SB,BDD,SĐ,SĐN,Khác,Total
0,Vinamilk,846346.0,2747674.0,921431.0,101221.0,295591.0,42488.0,411684.0,5366435.0
1,Nestlé,3239815.0,10602.0,1118095.0,19134.0,0.0,0.0,99299.0,4486945.0
2,FCV,137230.0,419067.0,1176748.0,0.0,5424.0,0.0,19766.0,1758235.0
3,Abbott,0.0,0.0,1107333.0,0.0,0.0,0.0,26464.0,1133797.0
4,Nutifood,51585.0,7410.0,699452.0,9.0,906.0,16789.0,72349.0,848500.0
5,TH True Milk,137920.0,51705.0,12830.0,0.0,0.0,11518.0,111155.0,325128.0
6,IDP,276051.0,23239.0,0.0,0.0,0.0,0.0,16010.0,315300.0
7,Mead Johnson,0.0,0.0,260414.0,0.0,0.0,0.0,4748.0,265162.0
8,Vinasoy,0.0,56270.0,0.0,0.0,0.0,174956.0,24447.0,255673.0
9,Vitadairy,22138.0,0.0,196991.0,0.0,0.0,0.0,20836.0,239965.0
10,Fonterra,0.0,0.0,107462.0,0.0,0.0,0.0,2086.0,109548.0
11,Nutricare,5522.0,1740.0,59822.0,108.0,0.0,25.0,5003.0,72220.0
12,Đà Lạt Milk,18571.0,1723.0,0.0,0.0,0.0,0.0,1523.0,21817.0
13,Hipp,0.0,0.0,12161.0,4362.0,0.0,0.0,2820.0,19343.0

In [24]:
#Số buzz theo tuần
filtered_sh_sentiment = sh_sentiment[((sh_sentiment["Thời gian"] == month)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
week = filtered_sh_sentiment.pivot_table(index='Tuần', columns='Thương hiệu', values='Total new', aggfunc='sum').round(decimals=0)
column_sums = week.sum(axis=0, numeric_only=True)
week.loc['Total'] = week.sum(numeric_only=True)
week.reset_index(inplace=True)
total_values = week.loc[week['Tuần'] == 'Total'].drop(columns=['Tuần']).iloc[0]
sorted_columns = total_values.sort_values(ascending=False).index
sorted_columns = ['Tuần'] + sorted_columns.tolist()
week = week[sorted_columns]
week

Thương hiệu,Tuần,Nestlé,Vitadairy,Vinamilk,Nutifood,Abbott,IDP,TH True Milk,FCV,Mead Johnson,Hipp,Nutricare,Fonterra,Vinasoy,Đà Lạt Milk
0,01/11/2024 - 07/11/2024,136285.0,44201.0,65451.0,24002.0,13627.0,14377.0,9650.0,8186.0,3135.0,1714.0,4613.0,7916.0,1823.0,1434.0
1,08/11/2024 - 14/11/2024,182195.0,34282.0,65625.0,27740.0,13794.0,10671.0,7613.0,7296.0,16112.0,2872.0,3835.0,2579.0,1472.0,1190.0
2,15/11/2024 - 21/11/2024,116779.0,51064.0,66066.0,22734.0,29314.0,8103.0,7848.0,6275.0,4719.0,4260.0,3554.0,968.0,1207.0,742.0
3,22/11/2024 - 28/11/2024,132641.0,283870.0,108694.0,25084.0,16253.0,11925.0,9410.0,9894.0,3180.0,2203.0,3951.0,2396.0,1716.0,541.0
4,29/11/2024 - 30/11/2024,58095.0,127008.0,80282.0,5779.0,4566.0,4295.0,1376.0,2573.0,1460.0,9139.0,983.0,2083.0,351.0,237.0
5,Total,625995.0,540425.0,386118.0,105339.0,77554.0,49371.0,35897.0,34224.0,28606.0,20188.0,16936.0,15942.0,6569.0,4144.0

In [25]:
#with pd.ExcelWriter(Link, engine='openpyxl',mode='a') as writer:
    #week.to_excel(writer, index=False, sheet_name='week')

In [26]:
#with pd.ExcelWriter(Link, engine='openpyxl') as writer:
    #SOV.to_excel(writer, sheet_name='Month', startrow=0, startcol=0, index=False)
    #brand_sent.to_excel(writer, sheet_name='Month', startrow=0, startcol=3, index=False)
    #week.to_excel(writer, sheet_name='Month', startrow=18, startcol=0, index=False)

In [27]:
sh_relevant["Thời gian"] = sh_relevant["Thời gian"].astype(str)
sh_sentiment["Thời gian"] = sh_sentiment["Thời gian"].astype(str)
sh_channel["Thời gian"] = sh_channel["Thời gian"].astype(str)

In [28]:
#Month_Thị phần ngành sữa theo Tháng năm 2024
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV = filtered_sh_sentiment.pivot_table(index='Thương hiệu',columns ='Thời gian', values ='Total new', aggfunc = sum).round()
SOV = SOV.sort_values(by=SOV.columns[-1],ascending=False)
SOV.reset_index(inplace=True)
SOV

Thời gian,Thương hiệu,2024-01-01,2024-02-01,2024-03-01,2024-04-01,2024-05-01,2024-06-01,2024-07-01,2024-08-01,2024-09-01,2024-10-01,2024-11-01
0,Nestlé,395300.0,262527.0,290834.0,1257711.0,599086.0,404083.0,432455.0,508305.0,409952.0,541990.0,625995.0
1,Vitadairy,35467.0,17287.0,36216.0,30947.0,43235.0,87055.0,777615.0,172012.0,149599.0,114002.0,540425.0
2,Vinamilk,975475.0,1098439.0,895256.0,493261.0,1086483.0,954176.0,404978.0,607849.0,340150.0,492792.0,386118.0
3,Nutifood,50854.0,37496.0,1064051.0,664963.0,321144.0,612156.0,108454.0,155981.0,103269.0,125324.0,105339.0
4,Abbott,157165.0,69971.0,52606.0,106687.0,106023.0,704597.0,140398.0,137821.0,183896.0,132908.0,77554.0
5,IDP,18692.0,34573.0,785805.0,75570.0,35512.0,54822.0,61227.0,78183.0,67218.0,61148.0,49371.0
6,TH True Milk,18513.0,14599.0,63764.0,78560.0,80097.0,86406.0,58345.0,257330.0,182040.0,244561.0,35897.0
7,FCV,33599.0,22038.0,52168.0,51514.0,66290.0,46819.0,38967.0,89133.0,32516.0,26906.0,34224.0
8,Mead Johnson,18280.0,16414.0,147037.0,40747.0,19785.0,20913.0,58781.0,19492.0,13000.0,21596.0,28606.0
9,Hipp,6251.0,3744.0,13634.0,21098.0,17744.0,15043.0,18556.0,20781.0,11207.0,11661.0,20188.0
10,Nutricare,6869.0,4878.0,8029.0,9878.0,6743.0,11429.0,7470.0,16288.0,18208.0,18670.0,16936.0
11,Fonterra,77607.0,1991.0,3964.0,62028.0,38271.0,11533.0,4328.0,19180.0,11742.0,17911.0,15942.0
12,Vinasoy,25113.0,9279.0,17584.0,7316.0,14736.0,74609.0,27287.0,25383.0,16034.0,17697.0,6569.0
13,Đà Lạt Milk,2098.0,2149.0,2967.0,3933.0,2504.0,5679.0,6570.0,11218.0,7884.0,5687.0,4144.0

In [29]:
#Thị phần ngành sữa theo Tháng năm 2024
filtered_sh_sentiment_ytd = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV_YTD = filtered_sh_sentiment_ytd.pivot_table(index='Thương hiệu',columns ='Thời gian', values ='Total new', aggfunc = sum).round().reset_index()
SOV_YTD['Total'] = SOV_YTD.sum(axis=1)
SOV_YTD = SOV_YTD.sort_values(by='Total',ascending=False)
SOV_YTD

C:\Users\Kompa-KTelt056\AppData\Local\Temp\ipykernel_1444\2583928609.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  SOV_YTD['Total'] = SOV_YTD.sum(axis=1)

Thời gian,Thương hiệu,2024-01-01,2024-02-01,2024-03-01,2024-04-01,2024-05-01,2024-06-01,2024-07-01,2024-08-01,2024-09-01,2024-10-01,2024-11-01,Total
10,Vinamilk,975475.0,1098439.0,895256.0,493261.0,1086483.0,954176.0,404978.0,607849.0,340150.0,492792.0,386118.0,7734977.0
6,Nestlé,395300.0,262527.0,290834.0,1257711.0,599086.0,404083.0,432455.0,508305.0,409952.0,541990.0,625995.0,5728238.0
7,Nutifood,50854.0,37496.0,1064051.0,664963.0,321144.0,612156.0,108454.0,155981.0,103269.0,125324.0,105339.0,3349031.0
12,Vitadairy,35467.0,17287.0,36216.0,30947.0,43235.0,87055.0,777615.0,172012.0,149599.0,114002.0,540425.0,2003860.0
0,Abbott,157165.0,69971.0,52606.0,106687.0,106023.0,704597.0,140398.0,137821.0,183896.0,132908.0,77554.0,1869626.0
4,IDP,18692.0,34573.0,785805.0,75570.0,35512.0,54822.0,61227.0,78183.0,67218.0,61148.0,49371.0,1322121.0
9,TH True Milk,18513.0,14599.0,63764.0,78560.0,80097.0,86406.0,58345.0,257330.0,182040.0,244561.0,35897.0,1120112.0
1,FCV,33599.0,22038.0,52168.0,51514.0,66290.0,46819.0,38967.0,89133.0,32516.0,26906.0,34224.0,494174.0
5,Mead Johnson,18280.0,16414.0,147037.0,40747.0,19785.0,20913.0,58781.0,19492.0,13000.0,21596.0,28606.0,404651.0
2,Fonterra,77607.0,1991.0,3964.0,62028.0,38271.0,11533.0,4328.0,19180.0,11742.0,17911.0,15942.0,264497.0
11,Vinasoy,25113.0,9279.0,17584.0,7316.0,14736.0,74609.0,27287.0,25383.0,16034.0,17697.0,6569.0,241607.0
3,Hipp,6251.0,3744.0,13634.0,21098.0,17744.0,15043.0,18556.0,20781.0,11207.0,11661.0,20188.0,159907.0
8,Nutricare,6869.0,4878.0,8029.0,9878.0,6743.0,11429.0,7470.0,16288.0,18208.0,18670.0,16936.0,125398.0
13,Đà Lạt Milk,2098.0,2149.0,2967.0,3933.0,2504.0,5679.0,6570.0,11218.0,7884.0,5687.0,4144.0,54833.0

In [30]:
with pd.ExcelWriter(Link, engine='openpyxl') as writer:
    SOV.to_excel(writer, sheet_name='Month', startrow=0, startcol=0, index=False)
    brand_sent.to_excel(writer, sheet_name='Month', startrow=17, startcol=0, index=False)
    week.to_excel(writer, sheet_name='Month', startrow=34, startcol=0, index=False)

In [31]:
with pd.ExcelWriter(Link, engine='openpyxl',mode='a',if_sheet_exists='overlay') as writer:
    SOV_YTD.to_excel(writer, sheet_name='YTD_SOV', startrow=0, startcol=0, index=False)
    SOV_pre_YTD.to_excel(writer, sheet_name='YTD_SOV', startrow=18, startcol=0, index=False)

In [32]:
#Sắc thái thảo luận của các thương hiệu YTD
filtered_sh_sentiment_YTD = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
sentiment_brand = filtered_sh_sentiment_YTD.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
sentiment_brand.columns =['YTD','Positive','Neutral','Negative','Total new']
sentiment_brand

             YTD   Positive    Neutral  Negative  Total new
0       Vinamilk  5521282.0  2210487.0    3208.0  7734977.0
1         Nestlé  5328077.0   399687.0     474.0  5728238.0
2       Nutifood  2820883.0   527094.0    1053.0  3349031.0
3      Vitadairy  1506051.0   497359.0     450.0  2003860.0
4         Abbott  1065321.0   789298.0   15007.0  1869626.0
5            IDP  1000086.0   315944.0    6091.0  1322121.0
6   TH True Milk   154773.0   963100.0    2239.0  1120112.0
7            FCV   138509.0   354819.0     847.0   494174.0
8   Mead Johnson   242732.0   160146.0    1773.0   404651.0
9       Fonterra   175896.0    88530.0      71.0   264497.0
10       Vinasoy   116020.0   125271.0     316.0   241607.0
11          Hipp    44795.0   114910.0     203.0   159907.0
12     Nutricare    13429.0   111865.0     104.0   125398.0
13   Đà Lạt Milk     2864.0    51949.0      20.0    54833.0

In [33]:
with pd.ExcelWriter(Link, engine='openpyxl',mode ='a',if_sheet_exists='overlay') as writer:
    brand_sent_pre_ytd.to_excel(writer, sheet_name='YTD_brand_sent', startrow=0, startcol=0, index=False)
    sentiment_brand.to_excel(writer, sheet_name='YTD_brand_sent', startrow=0, startcol=6, index=False)

In [34]:
#Category
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands))]
cate_ytd = filtered_sh_sentiment.pivot_table(index='Thương hiệu', columns='Ngành hàng', values='Total new', aggfunc='sum').round(decimals=0).fillna(0)
cate_ytd['Total'] = cate_ytd.sum(axis=1)
cate_ytd = cate_ytd.sort_values(by="Total",ascending=False)
cate_ytd.reset_index(inplace=True)
cate_ytd['BDD'] = cate_ytd[['BDD','BAD']].sum(axis=1)
cate_ytd['Khác'] = cate_ytd['Total'] - cate_ytd[['SN','SC','SB','BDD','SĐ','SĐN']].sum(axis=1)
cate_ytd = cate_ytd[['Thương hiệu','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']]
cate_ytd.columns = ['YTD','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']
cate_ytd

,YTD,SN,SC,SB,BDD,SĐ,SĐN,Khác,Total
0,Vinamilk,723646.0,3379594.0,2135638.0,75884.0,833097.0,40784.0,546334.0,7734977.0
1,Nestlé,2261624.0,8870.0,3205520.0,19042.0,0.0,0.0,233182.0,5728238.0
2,Nutifood,113661.0,7260.0,3041329.0,1061.0,1758.0,6687.0,177275.0,3349031.0
3,Vitadairy,59705.0,0.0,1853472.0,0.0,0.0,0.0,90683.0,2003860.0
4,Abbott,0.0,0.0,1844118.0,0.0,0.0,0.0,25508.0,1869626.0
5,IDP,1282613.0,33036.0,0.0,0.0,0.0,0.0,6472.0,1322121.0
6,TH True Milk,128138.0,74846.0,24197.0,0.0,0.0,34049.0,858882.0,1120112.0
7,FCV,87298.0,308320.0,87883.0,0.0,9160.0,0.0,1513.0,494174.0
8,Mead Johnson,0.0,0.0,403239.0,0.0,0.0,0.0,1412.0,404651.0
9,Fonterra,0.0,0.0,264147.0,0.0,0.0,0.0,350.0,264497.0
10,Vinasoy,0.0,11217.0,0.0,0.0,0.0,217591.0,12799.0,241607.0
11,Hipp,0.0,0.0,75234.0,18846.0,0.0,0.0,65827.0,159907.0
12,Nutricare,14678.0,2508.0,90076.0,1294.0,0.0,319.0,16523.0,125398.0
13,Đà Lạt Milk,47579.0,4335.0,0.0,0.0,0.0,0.0,2919.0,54833.0

In [35]:
with pd.ExcelWriter(Link, engine='openpyxl',mode ='a',if_sheet_exists='overlay') as writer:
    cate.to_excel(writer, sheet_name='YTD_cate', startrow=0, startcol=0, index=False)
    cate_ytd.to_excel(writer, sheet_name='YTD_cate', startrow=0, startcol=12, index=False)

In [36]:
#Relevant thảo luận của các thương hiệu YTD
filtered_sh_relevant_YTD = sh_relevant[(sh_relevant["Thời gian"].str.contains(year,na=False)) & ~sh_relevant["Thương hiệu"].isin(exclude_brands)]
relevant_brand = filtered_sh_relevant_YTD.groupby(["Thương hiệu"]).agg({"Relevant new": "sum","Irrelevant new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
relevant_brand

     Thương hiệu  Relevant new  Irrelevant new  Total new
0       Vinamilk     7270836.0        464141.0  7734977.0
1         Nestlé     5691760.0         36478.0  5728238.0
2       Nutifood     3145450.0        203581.0  3349031.0
3      Vitadairy     1985903.0         17957.0  2003860.0
4         Abbott     1712495.0        157131.0  1869626.0
5            IDP     1297691.0         24430.0  1322121.0
6   TH True Milk      583766.0        536346.0  1120112.0
7            FCV      465920.0         28254.0   494174.0
8   Mead Johnson      389564.0         15087.0   404651.0
9       Fonterra      237063.0         27434.0   264497.0
10       Vinasoy      221089.0         20518.0   241607.0
11          Hipp      147313.0         12594.0   159907.0
12     Nutricare      120960.0          4438.0   125398.0
13   Đà Lạt Milk       54590.0           243.0    54833.0

In [37]:
with pd.ExcelWriter(Link, engine='openpyxl', mode='a') as writer:
    relevant_brand.to_excel(writer, index=False, sheet_name='YTD_rlv')

In [38]:
# Thảo luận của các thương hiệu theo kênh YTD
filtered_sh_channel_YTD = sh_channel[(sh_channel["Thời gian"].str.contains(year,na=False)) & ~sh_channel["Thương hiệu"].isin(exclude_brands)]
channel_brand = filtered_sh_channel_YTD.groupby(["Thương hiệu"]).agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()  
channel_brand["Khác"] = channel_brand["Total new"] - channel_brand.drop(columns=["Thương hiệu", "Total new"]).sum(axis=1)
channel_brand = channel_brand[['Thương hiệu','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
channel_brand

,Thương hiệu,Fanpage new,FB page new,FB user new,FB group new,Tiktok new,Forum new,News new,Youtube new,Khác,Total new
0,Vinamilk,606431.0,1702204.0,4058796.0,945583.0,339747.0,27906,26078,18421,9812.0,7734978.0
1,Nestlé,631483.0,1880089.0,2269810.0,908071.0,34427.0,265,2631,400,1062.0,5728238.0
2,Nutifood,1963141.0,428453.0,607699.0,275217.0,67864.0,202,1621,1495,3339.0,3349031.0
3,Vitadairy,160952.0,536693.0,845563.0,412762.0,45965.0,59,257,528,1081.0,2003860.0
4,Abbott,410067.0,337324.0,497330.0,584845.0,39024.0,383,383,161,109.0,1869626.0
5,IDP,184513.0,162083.0,517248.0,75085.0,367366.0,194,1706,12687,1239.0,1322121.0
6,TH True Milk,82885.0,681935.0,142944.0,164453.0,31063.0,451,5285,10418,678.0,1120112.0
7,FCV,38371.0,148712.0,127464.0,135068.0,40889.0,92,361,2963,254.0,494174.0
8,Mead Johnson,1264.0,219334.0,54214.0,118576.0,9994.0,111,204,119,835.0,404651.0
9,Fonterra,26936.0,116695.0,103044.0,8834.0,8304.0,17,119,522,26.0,264497.0
10,Vinasoy,113396.0,27366.0,56441.0,29429.0,14032.0,15,642,256,30.0,241607.0
11,Hipp,13375.0,41806.0,16693.0,79645.0,8056.0,33,8,13,278.0,159907.0
12,Nutricare,6061.0,20830.0,51094.0,34177.0,12673.0,7,213,191,152.0,125398.0
13,Đà Lạt Milk,1125.0,10748.0,14843.0,26480.0,1193.0,26,128,72,218.0,54833.0

In [39]:
with pd.ExcelWriter(Link, engine='openpyxl', mode='a') as writer:
    channel_brand.to_excel(writer, index=False, sheet_name='YTD_channel')

# Ngành hàng

Sentiment, Relevant

In [40]:
def process_data(df, columns, nganh_hang, year):
    filtered_df = df[(df["Ngành hàng"] == nganh_hang) & (df["Thời gian"].str.contains(year, na=False))]
    
    grouped_df = filtered_df.groupby(["Sản phẩm"]).agg(columns).sort_values(by="Total new", ascending=False).reset_index().round()
    
    top_13 = grouped_df.head(13)
    khac = grouped_df.iloc[13:].agg(columns).to_frame().transpose()
    
    result_df = pd.concat([top_13, khac], ignore_index=True)
    result_df.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
    
    return result_df


# Define columns for Sentiment
sentiment_columns = { "Total new": "sum", "Positive new": "sum", "Neutral new": "sum", "Negative new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = Link
existing_excel = pd.ExcelFile(existing_excel_path)

with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    start_column = 0  # Initialize start column for each df
    for nganh_hang in nganh_hang_list:
        # Process data for each nganh_hang
        sentiment_data = process_data(sh_sentiment, sentiment_columns, nganh_hang, year)
        
        # Rename the 'Sản phẩm' column to the current 'nganh_hang' value
        sentiment_data.rename(columns={'Sản phẩm': nganh_hang}, inplace=True)
        
        # Display the sentiment_data for debugging
        print(f"Sentiment ({nganh_hang}):")
        print(sentiment_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        sentiment_data.to_excel(writer, sheet_name="Sentiment_Cate", startcol=start_column, index=False)
        
        # Adjust start column for the next DataFrame
        start_column += len(sentiment_data.columns) + 2  # Increment by number of columns + some padding

# Close the existing Excel file
existing_excel.close()

# Define columns for Relevant
relevant_columns = {"Relevant new": "sum","Irrelevant new": "sum","Total new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = Link
existing_excel = pd.ExcelFile(existing_excel_path)

with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    start_column = 0  # Initialize start column for each df
    for nganh_hang in nganh_hang_list:
        # Process data for each nganh_hang
        relevant_data = process_data(sh_relevant, relevant_columns, nganh_hang, year)
        
        # Rename the 'Sản phẩm' column to the current 'nganh_hang' value
        relevant_data.rename(columns={'Sản phẩm': nganh_hang}, inplace=True)
        
        # Display the sentiment_data for debugging
        print(f"Relevant ({nganh_hang}):")
        print(relevant_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        relevant_data.to_excel(writer, sheet_name="Relevant_Cate", startcol=start_column, index=False)
        
        # Adjust start column for the next DataFrame
        start_column += len(relevant_data.columns) + 2  # Increment by number of columns + some padding

# Close the existing Excel file
existing_excel.close()

Sentiment (SC):
                                     SC  Total new  Positive new  Neutral new  \
0                        Vinamilk Probi   948422.0      803955.0     143902.0
1                     Sữa chua Vinamilk   905474.0      722646.0     182584.0
2                         Vinamilk Susu   739357.0      629952.0     109313.0
3                         Vinamilk Hero   726821.0      628932.0      97885.0
4                                Yomost   299149.0       96453.0     202477.0
5                       Sữa chua Yakult    96452.0       30537.0      65571.0
6                         Sữa chua Hoff    60116.0        7494.0      52176.0
7                       Vinamilk Yomilk    58761.0       52137.0       6623.0
8                        TH True Yogurt    40348.0        6859.0      33218.0
9                       Sữa chua TOPKID    18126.0        4409.0      13675.0
10  Sữa chua uống men sống TH True Milk    16372.0        6595.0       9772.0
11                Sữa chua uống LIF KUN    14876.0        1044.0      13741.0
12                    Sữa chua ăn Ba Vì    13798.0         737.0      13059.0
13                        Sản phẩm khác    61090.0       16082.0      44978.0

    Negative new
0          565.0
1          244.0
2           92.0
3            4.0
4          219.0
5          344.0
6          445.0
7            1.0
8          271.0
9           41.0
10           5.0
11          91.0
12           1.0
13          29.0

==================================================

Sentiment (SN):
                           SN  Total new  Positive new  Neutral new  \
0                        Milo  2203117.0     2075989.0     126916.0
1                     LOF KUN  1183960.0      932761.0     245949.0
2               Vinamilk 100%   535901.0      477139.0      58745.0
3         Vinamilk Green Farm   121706.0       78469.0      43217.0
4      Sữa lúa mạch Lof Malto    67974.0       52280.0      15182.0
5       Sữa tươi TH True Milk    66851.0        8350.0      58032.0
6             Sữa nước Nestlé    58507.0         452.0      58055.0
7           Sữa tươi NutiMilk    53960.0       24404.0      29539.0
8   Sữa tươi Dutch Lady (RTD)    49549.0        2250.0      47252.0
9        Sữa tươi Đà Lạt Milk    47579.0        2605.0      44958.0
10                   Ovaltine    37747.0       22188.0      15440.0
11   Sữa non Colos Fresh Milk    29334.0       24664.0       4670.0
12          Sữa trái cây Oggi    28519.0        8710.0      19807.0
13              Sản phẩm khác   234238.0       59924.0     173406.0

    Negative new
0          213.0
1         5250.0
2           17.0
3           20.0
4          512.0
5          469.0
6            0.0
7           17.0
8           47.0
9           17.0
10         119.0
11           0.0
12           2.0
13         908.0

==================================================

Sentiment (SB):
                           SB  Total new  Positive new  Neutral new  \
0                   Nuvi Grow  1881839.0     1839766.0      42048.0
1                   Grow Plus  1094727.0      892689.0     201373.0
2                  Colos gain   841980.0      773129.0      68753.0
3   Vinamilk Dielac Grow Plus   837167.0      428460.0     408675.0
4               S-26 Ultima 3   756462.0      708280.0      48134.0
5                   ColosBaby   746132.0      571520.0     174348.0
6               Nan Optipro 4   741494.0      727114.0      14378.0
7             Similac Vietnam   705242.0      404370.0     299525.0
8                         Nan   693141.0      616655.0      76396.0
9         Abbott Grow Vietnam   571494.0      333047.0     237899.0
10           Nan Infinipro A2   529465.0      524041.0       5419.0
11         Vinamilk Yoko Gold   461707.0      439452.0      22225.0
12              Nan Supreme 3   375183.0      360325.0      14858.0
13              Sản phẩm khác  2788820.0     1724758.0    1048997.0

    Negative new
0           25.0
1          664.0
2           98.0
3           32.0
4           48.0
5          264.0
6            2.0
7         1346.0
8           90.0
9          548.0
10           5.0
11          30.0
12           0.0
13       15059.0

==================================================

Sentiment (SĐ):
                              SĐ  Total new  Positive new  Neutral new  \
0               Vinamilk Ông thọ   785970.0      365437.0     420382.0
1   Vinamilk Ngôi Sao Phương Nam    27600.0        3497.0      24101.0
2               Sữa đặc Vinamilk    14709.0         287.0      14422.0
3             Sữa đặc Dutch Lady     8920.0         163.0       8757.0
4               Vinamilk Tài lộc     4818.0          73.0       4743.0
5               Sữa đặc Nutifood     1758.0         177.0       1581.0
6               Sữa đặc Hoàn Hảo      240.0           1.0        239.0
7                            NaN        0.0           0.0          0.0
13                 Sản phẩm khác        NaN           NaN          NaN

    Negative new
0          151.0
1            2.0
2            0.0
3            0.0
4            2.0
5            0.0
6            0.0
7            0.0
13           NaN

==================================================

Sentiment (SĐN):
                         SĐN  Total new  Positive new  Neutral new  \
0                       Fami   208682.0       98618.0     109765.0
1                TH True Nut    30035.0        2474.0      27464.0
2         Vinamilk Super Nut    23060.0        4396.0      18648.0
3               Sữa hạt Veyo     8851.0        5434.0       3413.0
4      Sữa đậu nành Nutifood     6687.0         273.0       6414.0
5        Vinamilk Hạt Óc Chó     5697.0        1559.0       4104.0
6         Vinamilk Hạnh Nhân     3617.0        1421.0       2192.0
7            Vinamilk Đậu Đỏ     3592.0        1414.0       2176.0
8                TH true OAT     2994.0         609.0       2383.0
9      Sữa Đậu Nành Vinamilk     2556.0        1014.0       1532.0
10  Vinamilk Sữa hạt Cao Đạm     2189.0         284.0       1901.0
11        TH True Light Meal     1020.0         210.0        793.0
12             Nunut Lục Bảo      319.0           0.0        319.0
13             Sản phẩm khác      131.0          14.0        117.0

    Negative new
0          299.0
1           97.0
2           16.0
3            4.0
4            0.0
5           34.0
6            4.0
7            2.0
8            2.0
9           10.0
10           4.0
11          17.0
12           0.0
13           0.0

==================================================

Relevant (SC):
                                     SC  Relevant new  Irrelevant new  \
0                        Vinamilk Probi      876561.0         71861.0
1                     Sữa chua Vinamilk      849087.0         56387.0
2                         Vinamilk Susu      676292.0         63065.0
3                         Vinamilk Hero      664067.0         62754.0
4                                Yomost      284549.0         14600.0
5                       Sữa chua Yakult       80569.0         15883.0
6                         Sữa chua Hoff       58223.0          1893.0
7                       Vinamilk Yomilk       53477.0          5284.0
8                        TH True Yogurt       37455.0          2893.0
9                       Sữa chua TOPKID       18068.0            58.0
10  Sữa chua uống men sống TH True Milk       16345.0            27.0
11                Sữa chua uống LIF KUN       13901.0           975.0
12                    Sữa chua ăn Ba Vì       13787.0            11.0
13                        Sản phẩm khác       58033.0          3057.0

    Total new
0    948422.0
1    905474.0
2    739357.0
3    726821.0
4    299149.0
5     96452.0
6     60116.0
7     58761.0
8     40348.0
9     18126.0
10    16372.0
11    14876.0
12    13798.0
13    61090.0

==================================================

Relevant (SN):
                           SN  Relevant new  Irrelevant new  Total new
0                        Milo     2180237.0         22880.0  2203117.0
1                     LOF KUN     1164734.0         19226.0  1183960.0
2               Vinamilk 100%      512175.0         23726.0   535901.0
3         Vinamilk Green Farm      115050.0          6656.0   121706.0
4      Sữa lúa mạch Lof Malto       65542.0          2432.0    67974.0
5       Sữa tươi TH True Milk       66570.0           281.0    66851.0
6             Sữa nước Nestlé       58507.0             0.0    58507.0
7           Sữa tươi NutiMilk       48885.0          5075.0    53960.0
8   Sữa tươi Dutch Lady (RTD)       44405.0          5144.0    49549.0
9        Sữa tươi Đà Lạt Milk       47369.0           210.0    47579.0
10                   Ovaltine       34336.0          3411.0    37747.0
11   Sữa non Colos Fresh Milk       29246.0            88.0    29334.0
12          Sữa trái cây Oggi       27322.0          1197.0    28519.0
13              Sản phẩm khác      225946.0          8292.0   234238.0

==================================================

Relevant (SB):
                           SB  Relevant new  Irrelevant new  Total new
0                   Nuvi Grow     1858810.0         23029.0  1881839.0
1                   Grow Plus     1033755.0         60972.0  1094727.0
2                  Colos gain      838429.0          3551.0   841980.0
3   Vinamilk Dielac Grow Plus      782776.0         54391.0   837167.0
4               S-26 Ultima 3      756123.0           339.0   756462.0
5                   ColosBaby      739640.0          6492.0   746132.0
6               Nan Optipro 4      739081.0          2413.0   741494.0
7             Similac Vietnam      651741.0         53501.0   705242.0
8                         Nan      683659.0          9482.0   693141.0
9         Abbott Grow Vietnam      518808.0         52686.0   571494.0
10           Nan Infinipro A2      528891.0           574.0   529465.0
11         Vinamilk Yoko Gold      449852.0         11855.0   461707.0
12              Nan Supreme 3      375148.0            35.0   375183.0
13              Sản phẩm khác     2627350.0        161470.0  2788820.0

==================================================

Relevant (SĐ):
                              SĐ  Relevant new  Irrelevant new  Total new
0               Vinamilk Ông thọ      748008.0         37962.0   785970.0
1   Vinamilk Ngôi Sao Phương Nam       26599.0          1001.0    27600.0
2               Sữa đặc Vinamilk       14558.0           151.0    14709.0
3             Sữa đặc Dutch Lady        8920.0             0.0     8920.0
4               Vinamilk Tài lộc        4776.0            42.0     4818.0
5               Sữa đặc Nutifood        1756.0             2.0     1758.0
6               Sữa đặc Hoàn Hảo         240.0             0.0      240.0
7                            NaN           0.0             0.0        0.0
13                 Sản phẩm khác           NaN             NaN        NaN

==================================================

Relevant (SĐN):
                         SĐN  Relevant new  Irrelevant new  Total new
0                       Fami      192052.0         16630.0   208682.0
1                TH True Nut       29986.0            49.0    30035.0
2         Vinamilk Super Nut       21484.0          1576.0    23060.0
3               Sữa hạt Veyo        7578.0          1273.0     8851.0
4      Sữa đậu nành Nutifood        6682.0             5.0     6687.0
5        Vinamilk Hạt Óc Chó        5262.0           435.0     5697.0
6         Vinamilk Hạnh Nhân        3274.0           343.0     3617.0
7            Vinamilk Đậu Đỏ        3250.0           342.0     3592.0
8                TH true OAT        2994.0             0.0     2994.0
9      Sữa Đậu Nành Vinamilk        1933.0           623.0     2556.0
10  Vinamilk Sữa hạt Cao Đạm        2144.0            45.0     2189.0
11        TH True Light Meal        1001.0            19.0     1020.0
12             Nunut Lục Bảo         319.0             0.0      319.0
13             Sản phẩm khác         131.0             0.0      131.0

==================================================

In [41]:
#Sentiment BDD

filtered_sh_sentiment_BDD = sh_sentiment[(sh_sentiment["Ngành hàng"].isin(bdd)) & (sh_sentiment["Thời gian"].str.contains(year, na=False))]
sentiment_BDD = filtered_sh_sentiment_BDD.groupby(["Sản phẩm"]).agg(sentiment_columns).sort_values(by="Total new", ascending=False).reset_index().round()

sentiment_BDD_top_13 = sentiment_BDD.head(13)

SP_khac = sentiment_BDD.iloc[13:].agg(sentiment_columns).to_frame().transpose()
    
sentiment_BDD = pd.concat([sentiment_BDD_top_13, SP_khac], ignore_index=True)
sentiment_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
#sentiment_BDD.loc[13, 'Khác'] = sentiment_BDD.loc[13, 'Total new']
sentiment_BDD.rename(columns={'Sản phẩm': 'BDD'}, inplace=True)
sentiment_BDD

,BDD,Total new,Positive new,Neutral new,Negative new
0,Vinamilk Ridielac,75123.0,50617.0,24502.0,4.0
1,Gerber,18859.0,1220.0,17635.0,4.0
2,Bột ăn dặm Hipp,18846.0,1304.0,17526.0,15.0
3,Bột ăn dặm Metacare,1253.0,34.0,1219.0,0.0
4,Bột ăn dặm Nuti IQ,1061.0,331.0,730.0,0.0
5,Bột Dinh Dưỡng Vinamilk,666.0,142.0,524.0,0.0
6,Cerelac,183.0,27.0,156.0,0.0
7,Bột ăn dặm Vinamilk Optimum Gold,94.0,2.0,92.0,0.0
8,Bột ăn dặm Coloscare,41.0,0.0,41.0,0.0
9,Bột ăn dặm Vinamilk Organic Gold,1.0,0.0,1.0,0.0
10,NaN,0.0,0.0,0.0,0.0
13,Sản phẩm khác,NaN,NaN,NaN,NaN

In [42]:
with pd.ExcelWriter(Link, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    sentiment_BDD.to_excel(writer, sheet_name='Sentiment_Cate', startrow=0, startcol=35, index=False)

In [43]:
#Relevant BDD

filtered_sh_relevant_BDD = sh_relevant[(sh_relevant["Ngành hàng"].isin(bdd)) & (sh_relevant["Thời gian"].str.contains(year, na=False))]
relevant_BDD = filtered_sh_relevant_BDD.groupby(["Sản phẩm"]).agg(relevant_columns).sort_values(by="Total new", ascending=False).reset_index().round()

relevant_BDD_top_13 = relevant_BDD.head(13)

SP_khac = relevant_BDD.iloc[13:].agg(relevant_columns).to_frame().transpose()
    
relevant_BDD = pd.concat([relevant_BDD_top_13, SP_khac], ignore_index=True)
relevant_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
#relevant_BDD.loc[13, 'Khác'] = relevant_BDD.loc[13, 'Total new']
relevant_BDD.rename(columns={'Sản phẩm': 'BDD'}, inplace=True)
relevant_BDD

                                 BDD  Relevant new  Irrelevant new  Total new
0                  Vinamilk Ridielac       67972.0          7151.0    75123.0
1                             Gerber       18859.0             0.0    18859.0
2                    Bột ăn dặm Hipp       18555.0           291.0    18846.0
3                Bột ăn dặm Metacare        1251.0             2.0     1253.0
4                 Bột ăn dặm Nuti IQ        1058.0             3.0     1061.0
5            Bột Dinh Dưỡng Vinamilk         666.0             0.0      666.0
6                            Cerelac         183.0             0.0      183.0
7   Bột ăn dặm Vinamilk Optimum Gold          94.0             0.0       94.0
8               Bột ăn dặm Coloscare          41.0             0.0       41.0
9   Bột ăn dặm Vinamilk Organic Gold           1.0             0.0        1.0
10                               NaN           0.0             0.0        0.0
13                     Sản phẩm khác           NaN             NaN        NaN

In [44]:
with pd.ExcelWriter(Link, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    relevant_BDD.to_excel(writer, sheet_name='Relevant_Cate', startrow=0, startcol=29, index=False)

Channel

In [45]:
def process_data_channel(df, columns, nganh_hang, year):
    filtered_df = df[(df["Ngành hàng"] == nganh_hang) & (df["Thời gian"].str.contains(year, na=False))]
    
    grouped_df = filtered_df.groupby(["Sản phẩm"]).agg(columns).sort_values(by="Total new", ascending=False).reset_index().round()
    
    grouped_df["Khác"] = grouped_df["Total new"] - grouped_df.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)
    
    top_13 = grouped_df.head(13)
    khac = grouped_df.iloc[13:].agg(columns).to_frame().transpose()
    
    result_df = pd.concat([top_13, khac], ignore_index=True)
    result_df.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
    result_df.loc[13, 'Khác'] = result_df.loc[13, 'Total new'] - result_df.loc[13, ['Fanpage new', 'FB page new', 'FB user new', 'FB group new', 'Tiktok new', 'Forum new', 'News new', 'Youtube new']].sum()
    result_df = result_df[['Sản phẩm','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
    
    return result_df

# Define columns for Channel
channel_columns = {"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = Link
existing_excel = pd.ExcelFile(existing_excel_path)

with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    start_column = 0  # Initialize start column for each df
    for nganh_hang in nganh_hang_list:
        # Process data for each nganh_hang
        channel_data = process_data(sh_channel, channel_columns, nganh_hang, year)
        
        # Rename the 'Sản phẩm' column to the current 'nganh_hang' value
        channel_data.rename(columns={'Sản phẩm': nganh_hang}, inplace=True)
        
        # Display the sentiment_data for debugging
        print(f"Channel ({nganh_hang}):")
        print(channel_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        channel_data.to_excel(writer, sheet_name="Channel_Cate", startcol=start_column, index=False)
        
        # Adjust start column for the next DataFrame
        start_column += len(channel_data.columns) + 2  # Increment by number of columns + some padding

# Close the existing Excel file
existing_excel.close()

Channel (SC):
                                     SC  Fanpage new  FB page new  \
0                        Vinamilk Probi      12188.0     512271.0
1                     Sữa chua Vinamilk      74917.0     228015.0
2                         Vinamilk Susu     190885.0     168579.0
3                         Vinamilk Hero     189359.0     167720.0
4                                Yomost      11465.0     129346.0
5                       Sữa chua Yakult      15539.0      24746.0
6                         Sữa chua Hoff       1562.0      15955.0
7                       Vinamilk Yomilk       2533.0       9463.0
8                        TH True Yogurt       9483.0      16518.0
9                       Sữa chua TOPKID       1750.0       7194.0
10  Sữa chua uống men sống TH True Milk       5654.0       3648.0
11                Sữa chua uống LIF KUN        427.0       2198.0
12                    Sữa chua ăn Ba Vì        100.0       1336.0
13                        Sản phẩm khác       9873.0       7081.0

    FB user new  FB group new  Tiktok new  Forum new  News new  Youtube new  \
0      360417.0       30573.0     30534.0       71.0       5.0        777.0
1      521650.0       62510.0     17086.0       75.0      34.0        166.0
2      319166.0        5966.0     48702.0        0.0      24.0       6022.0
3      314563.0         917.0     48446.0        0.0      23.0       5791.0
4       82975.0       36211.0     36922.0       18.0      58.0       1981.0
5       23175.0        9999.0     22537.0      118.0      84.0        199.0
6       28053.0        9244.0      5263.0        3.0       0.0         11.0
7       43473.0         206.0      3075.0        0.0       0.0          7.0
8        6957.0        5863.0       998.0       20.0     286.0        146.0
9        4468.0        4469.0       168.0        0.0      32.0         40.0
10       3105.0        3432.0       400.0        0.0      85.0         42.0
11       5423.0        3521.0      1779.0        1.0      59.0       1464.0
12       7453.0        4511.0        75.0       19.0     164.0          8.0
13      24416.0       13894.0      5207.0       22.0     162.0        349.0

    Total new
0    948422.0
1    905474.0
2    739357.0
3    726821.0
4    299149.0
5     96452.0
6     60116.0
7     58761.0
8     40348.0
9     18126.0
10    16372.0
11    14876.0
12    13798.0
13    61090.0

==================================================

Channel (SN):
                           SN  Fanpage new  FB page new  FB user new  \
0                        Milo      12298.0     881548.0    1133152.0
1                     LOF KUN     152475.0     140539.0     481039.0
2               Vinamilk 100%       7719.0      66580.0     405394.0
3         Vinamilk Green Farm       1688.0      58071.0      43742.0
4      Sữa lúa mạch Lof Malto      27402.0       9022.0       8144.0
5       Sữa tươi TH True Milk       4694.0       7940.0       9500.0
6             Sữa nước Nestlé          7.0       6873.0      33126.0
7           Sữa tươi NutiMilk       3035.0      25965.0       8208.0
8   Sữa tươi Dutch Lady (RTD)       5479.0       4158.0      10906.0
9        Sữa tươi Đà Lạt Milk       1059.0       9037.0      12733.0
10                   Ovaltine      17811.0       1966.0      13302.0
11   Sữa non Colos Fresh Milk      15888.0       2580.0      10029.0
12          Sữa trái cây Oggi       1719.0      13847.0      10094.0
13              Sản phẩm khác      32152.0      44936.0      67702.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0       160330.0     14718.0       57.0     781.0        209.0  2203117.0
1        58599.0    339495.0      106.0     586.0      10048.0  1183960.0
2        28470.0     27530.0        0.0       0.0        105.0   535901.0
3         2639.0     13973.0        5.0     665.0        462.0   121706.0
4         1362.0     20952.0        0.0      29.0       1057.0    67974.0
5        40964.0      2708.0      188.0     566.0        204.0    66851.0
6        18098.0       352.0        1.0      24.0         10.0    58507.0
7         8060.0      8405.0        2.0      92.0        134.0    53960.0
8        27912.0       942.0       17.0      64.0         55.0    49549.0
9        23269.0      1137.0       17.0      52.0         60.0    47579.0
10        2324.0      1736.0       21.0       5.0        571.0    37747.0
11         810.0        16.0        0.0       0.0          0.0    29334.0
12        2617.0       182.0        0.0       2.0         54.0    28519.0
13       66485.0     19865.0      129.0     363.0        810.0   234238.0

==================================================

Channel (SB):
                           SB  Fanpage new  FB page new  FB user new  \
0                   Nuvi Grow    1778982.0      34525.0      49388.0
1                   Grow Plus     173771.0     209850.0     478884.0
2                  Colos gain      11748.0     305090.0     361805.0
3   Vinamilk Dielac Grow Plus       5683.0      21035.0     734677.0
4               S-26 Ultima 3     353034.0     241773.0     101792.0
5                   ColosBaby     107168.0      97815.0     337267.0
6               Nan Optipro 4      34769.0     308815.0     278465.0
7             Similac Vietnam       7081.0     187745.0      25603.0
8                         Nan      23793.0      78246.0     161200.0
9         Abbott Grow Vietnam     371590.0      17088.0     149074.0
10           Nan Infinipro A2      72304.0     144451.0     268168.0
11         Vinamilk Yoko Gold       3342.0      39966.0     347872.0
12              Nan Supreme 3     103732.0      97533.0     121904.0
13              Sản phẩm khác     186008.0     776721.0    1129974.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0        14299.0      4398.0        0.0      52.0        137.0  1881839.0
1       193757.0     35559.0       25.0     121.0        572.0  1094727.0
2       149881.0     13100.0        0.0       2.0         43.0   841980.0
3        44491.0     31193.0        4.0       3.0         45.0   837167.0
4        55758.0      4082.0        1.0       0.0         12.0   756462.0
5       177699.0     25468.0       21.0      75.0        146.0   746132.0
6       118976.0       426.0        3.0       3.0         21.0   741494.0
7       469045.0     15485.0      125.0      19.0        116.0   705242.0
8       422073.0      7678.0       30.0       3.0         28.0   693141.0
9        21451.0     12242.0        8.0      22.0          7.0   571494.0
10       42047.0      2014.0        1.0       0.0         24.0   529465.0
11       65307.0      5101.0        6.0       3.0          9.0   461707.0
12       49944.0      1656.0        0.0       0.0         23.0   375183.0
13      571661.0    118201.0      643.0    2429.0       1758.0  2788820.0

==================================================

Channel (SĐ):
                              SĐ  Fanpage new  FB page new  FB user new  \
0               Vinamilk Ông thọ       4603.0     217418.0     313512.0
1   Vinamilk Ngôi Sao Phương Nam         22.0       7671.0       5834.0
2               Sữa đặc Vinamilk          0.0        283.0       3098.0
3             Sữa đặc Dutch Lady          0.0        743.0       4838.0
4               Vinamilk Tài lộc          1.0        156.0       2146.0
5               Sữa đặc Nutifood          0.0        540.0        340.0
6               Sữa đặc Hoàn Hảo          0.0          6.0         15.0
7                            NaN          0.0          0.0          0.0
13                 Sản phẩm khác          NaN          NaN          NaN

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0       232045.0     14424.0      145.0     786.0       2404.0   785970.0
1        12948.0       920.0       14.0      99.0         58.0    27600.0
2        11190.0        32.0        2.0      83.0         17.0    14709.0
3         3321.0         6.0        3.0       6.0          2.0     8920.0
4         2419.0        89.0        0.0       0.0          4.0     4818.0
5          854.0        17.0        0.0       6.0          0.0     1758.0
6          219.0         0.0        0.0       0.0          0.0      240.0
7            0.0         0.0        0.0       0.0          0.0        0.0
13           NaN         NaN        NaN       NaN          NaN        NaN

==================================================

Channel (SĐN):
                         SĐN  Fanpage new  FB page new  FB user new  \
0                       Fami      99277.0      24408.0      48581.0
1                TH True Nut       3526.0       5092.0      17236.0
2         Vinamilk Super Nut       2039.0      10699.0       4897.0
3               Sữa hạt Veyo       3272.0        504.0       2230.0
4      Sữa đậu nành Nutifood          0.0        360.0       3929.0
5        Vinamilk Hạt Óc Chó       2568.0       1451.0        893.0
6         Vinamilk Hạnh Nhân       2607.0         99.0        311.0
7            Vinamilk Đậu Đỏ       2606.0        104.0        281.0
8                TH true OAT        579.0       1527.0        563.0
9      Sữa Đậu Nành Vinamilk       1619.0        154.0        440.0
10  Vinamilk Sữa hạt Cao Đạm        168.0        281.0       1078.0
11        TH True Light Meal        498.0        200.0        112.0
12             Nunut Lục Bảo          2.0         50.0        246.0
13             Sản phẩm khác          1.0         21.0         77.0

    FB group new  Tiktok new  Forum new  News new  Youtube new  Total new
0        26205.0      9702.0       14.0     226.0        245.0   208682.0
1         3698.0       285.0       15.0     122.0         45.0    30035.0
2         2102.0      2830.0        0.0      82.0         17.0    23060.0
3           57.0      2756.0        0.0      29.0          0.0     8851.0
4         2381.0        10.0        0.0       3.0          3.0     6687.0
5          757.0         7.0        2.0       0.0          4.0     5697.0
6          563.0         1.0        1.0       0.0          0.0     3617.0
7          579.0         4.0        0.0       1.0          0.0     3592.0
8          198.0        42.0        0.0      69.0          7.0     2994.0
9          243.0         9.0        1.0       4.0          1.0     2556.0
10         351.0       145.0        5.0      40.0          0.0     2189.0
11         128.0         7.0        0.0      32.0         43.0     1020.0
12          21.0         0.0        0.0       0.0          0.0      319.0
13          18.0         2.0        0.0       4.0          5.0      131.0

==================================================

In [46]:
# Channel BDD
filtered_sh_channel_BDD = sh_channel[(sh_channel["Ngành hàng"].isin(bdd)) & (sh_channel["Thời gian"].str.contains(year, na=False))]
channel_BDD = filtered_sh_channel_BDD.groupby(["Sản phẩm"]).agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()  
channel_BDD["Khác"] = channel_BDD["Total new"] - channel_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

channel_BDD_top_13 = channel_BDD.head(13)

SP_khac = channel_BDD.iloc[13:].agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).to_frame().transpose()
    
channel_BDD = pd.concat([channel_BDD_top_13, SP_khac], ignore_index=True)
channel_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
channel_BDD.loc[13, 'Khác'] = channel_BDD.loc[13, 'Total new'] - channel_BDD.loc[13, ['Fanpage new', 'FB page new', 'FB user new', 'FB group new', 'Tiktok new', 'Forum new', 'News new', 'Youtube new']].sum()
channel_BDD = channel_BDD[['Sản phẩm','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
channel_BDD.rename(columns={'Sản phẩm': 'BDD'}, inplace=True)
channel_BDD

,BDD,Fanpage new,FB page new,FB user new,FB group new,Tiktok new,Forum new,News new,Youtube new,Khác,Total new
0,Vinamilk Ridielac,6237.0,4188.0,54058.0,3710.0,6909.0,2.0,4.0,5.0,10.0,75123.0
1,Gerber,127.0,10328.0,6485.0,1776.0,124.0,2.0,6.0,5.0,6.0,18859.0
2,Bột ăn dặm Hipp,107.0,8079.0,5985.0,3995.0,598.0,2.0,0.0,2.0,78.0,18846.0
3,Bột ăn dặm Metacare,72.0,422.0,650.0,98.0,9.0,1.0,0.0,0.0,1.0,1253.0
4,Bột ăn dặm Nuti IQ,1.0,393.0,227.0,417.0,23.0,0.0,0.0,0.0,0.0,1061.0
5,Bột Dinh Dưỡng Vinamilk,1.0,121.0,248.0,187.0,10.0,1.0,97.0,1.0,0.0,666.0
6,Cerelac,1.0,45.0,81.0,46.0,1.0,0.0,0.0,1.0,8.0,183.0
7,Bột ăn dặm Vinamilk Optimum Gold,1.0,4.0,13.0,75.0,0.0,0.0,1.0,0.0,0.0,94.0
8,Bột ăn dặm Coloscare,0.0,8.0,30.0,3.0,0.0,0.0,0.0,0.0,0.0,41.0
9,Bột ăn dặm Vinamilk Organic Gold,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
13,Sản phẩm khác,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
with pd.ExcelWriter(Link, engine='openpyxl', mode='a',if_sheet_exists='overlay') as writer:
    channel_BDD.to_excel(writer, sheet_name='Channel_Cate', startrow=0, startcol=60, index=False)