In [1]:
import pandas as pd
import re

In [2]:
sh_sentiment = pd.read_excel(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\Tính 23.07.2024.xlsx", sheet_name='Sentiment')
sh_relevant = pd.read_excel(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\Tính 23.07.2024.xlsx", sheet_name='Relevant')
sh_channel = pd.read_excel(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\Tính 23.07.2024.xlsx", sheet_name='Channel')

# Phân tích biến

Sheet Sentiment

In [3]:
sh_sentiment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15645 entries, 0 to 15644
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Thương hiệu       15645 non-null  object
 1   Ngành hàng        15645 non-null  object
 2   Sản phẩm          15645 non-null  object
 3   Thời gian         15645 non-null  datetime64[ns]
 4   Tuần              15645 non-null  object
 5   Positive          10673 non-null  float64
 6   Neutral           15397 non-null  float64
 7   Negative          5430 non-null   float64
 8   Blank             5429 non-null   float64
 9   Total after       15645 non-null  float64
 10  Blank.1           15644 non-null  float64
 11  Total             15645 non-null  float64
 12  Buzzes thêm       330 non-null    float64
 13  Sum of comments   11677 non-null  float64
 14  Sum of shares     11677 non-null  float64
 15  Positive new      15561 non-null  float64
 16  Neutral new       15645 non-null  float64
 17  Negative new      15431 non-null  float64
 18  Total new         15645 non-null  float64
 19  Check Total Buzz  15645 non-null  int64
 20  Ghi chú           491 non-null    object
 21  Số campaign       175 non-null    object
 22  Phân loại         15645 non-null  object
dtypes: datetime64[ns](1), float64(14), int64(1), object(7)
memory usage: 2.7+ MB

In [4]:
object_columns = list(sh_sentiment.select_dtypes(['object']).columns)
object_columns

['Thương hiệu',
 'Ngành hàng',
 'Sản phẩm',
 'Tuần',
 'Ghi chú',
 'Số campaign',
 'Phân loại']

In [5]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_sentiment[column].unique()), "unique values", "\t & \t", 
          sh_sentiment[column].notnull().sum(), "non-null values\t", 
          round(100* sh_sentiment[column].notnull().sum()/len(sh_sentiment[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 15645 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 15645 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
274 unique values 	 & 	 15645 non-null values	 100.0 % non-null
*, Column:  Tuần
89 unique values 	 & 	 15645 non-null values	 100.0 % non-null
*, Column:  Ghi chú
293 unique values 	 & 	 491 non-null values	 3.14 % non-null
*, Column:  Số campaign
107 unique values 	 & 	 175 non-null values	 1.12 % non-null
*, Column:  Phân loại
17 unique values 	 & 	 15645 non-null values	 100.0 % non-null

In [6]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_sentiment[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        4108
TH True Milk    1749
Nutifood        1636
Nutricare       1388
Vitadairy       1328
Nestlé          1205
FCV              833
IDP              685
Mead Johnson     586
Abbott           534
Vinasoy          324
Đà Lạt Milk      287
Hipp             267
Fonterra         253
Yakult           178
Betagen          172
Hoff             112
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       5752
SN       2764
SC       2124
BRAND    1319
NGK       938
SĐN       893
SĐ        544
KEM       513
BAD       306
BDD       189
BƠ         85
PM         68
ĐƯỜNG      61
FOOD       54
Brand      30
TUNL        5
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
ColosBaby               93
Vinamilk 100%           91
Vinamilk Fino           89
Sữa bột Hipp            89
Thương hiệu Nutifood    89
                        ..
Sữa non Colos Baby       1
Nunest Kid               1
GrandCare                1
Leanmax Colostrum        1
Vinamilk Platinum        1
Name: Sản phẩm, Length: 274, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Tuần
08/06/2024 - 14/06/2024    215
08/12/2023 - 14/12/2023    212
22/06/2024 - 28/06/2024    210
22/05/2024 - 28/05/2024    210
15/11/2023 - 21/11/2023    209
                          ...
29/03/2023 - 31/03/2023    123
29/01/2023 - 31/01/2023    120
29/05/2023 - 31/05/2023    118
22/01/2023 - 28/01/2023    114
29/04/2023 - 30/04/2023    111
Name: Tuần, Length: 89, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
rao vặt                                                                                                                                                                                         59
minigame trên fanpage                                                                                                                                                                           14
không lấy shares ảo                                                                                                                                                                              7
rao vặt sản phẩm                                                                                                                                                                                 6
#NutifoodThuyDien #Varna #Thanhxuanmaichay #khuyenmai                                                                                                                                            5
                                                                                                                                                                                                ..
minigame "Đáp trúng, nhận quà" trên fanpge Lazada Super Moms                                                                                                                                     1
minigame trên fanpage Nestlé Mom&Me Vietnam http://facebook.com/159267667447549_796314005515379 và  livestream trên fanpage KidsPlaza.vn http://facebook.com/159267667447549_796314005515379     1
minigame trên fanpage Nestlé Mom&Me Vietnam http://facebook.com/400564340152929_699671105531096                                                                                                  1
các bài review sản phẩm từ mẹ bỉm                                                                                                                                                                1
3000 Positive FBuser Công dụng Vinamilk 100% - 1 Lít Không Đường                                                                                                                                 1
Name: Ghi chú, Length: 292, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Số campaign
5000                                                                   13
800                                                                     6
400 buzzes : #NutifoodThuyDien #Varna #Thanhxuanmaichay #khuyenmai      5
#YomostVFLSummer2023 #MotCamGiacRatYomost #Yomost                       5
500                                                                     5
                                                                       ..
1000: #NANSupremePro3 #nguanguycodiung #Tangdekhang #danggoitienloi     1
2500: #NutrenJunior #TangTruong3Chuan #NestléHealthScience              1
#NestleS26Ultima3 #ChonDinhDuongKhoaHoc #TangTocDoKetNoiNaoBo           1
1500: #NANGrow #Caolonvuottroi #100%canxi #vitaminD3                    1
2,000 buzzes campagin Pediasure - Influencer Livestream                 1
Name: Số campaign, Length: 106, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Phân loại
SBTE     4017
SN       2764
SBNL     1735
BRAND    1349
SCU      1270
NGK       938
SĐN       893
SCA       854
SĐ        544
KEM       513
BAD       306
BDD       189
BƠ         85
PM         68
ĐƯỜNG      61
FOOD       54
TUNL        5
Name: Phân loại, dtype: int64
----------------------------------------------------------------------------------------------------

Sheet Relevant

In [7]:
sh_relevant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3590 entries, 0 to 3589
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Thương hiệu       3590 non-null   object
 1   Ngành hàng        3590 non-null   object
 2   Sản phẩm          3590 non-null   object
 3   Thời gian         3590 non-null   datetime64[ns]
 4   Relevant          3581 non-null   float64
 5   Irrelevant        2281 non-null   float64
 6   Blank             1293 non-null   float64
 7   Total after       3590 non-null   int64
 8   Total             3590 non-null   float64
 9   Buzzes thêm       193 non-null    float64
 10  Relevant new      3590 non-null   float64
 11  Irrelevant new    3590 non-null   float64
 12  Total new         3590 non-null   float64
 13  Check Total Buzz  3590 non-null   int64
 14  Ghi chú           4 non-null      object
dtypes: datetime64[ns](1), float64(8), int64(2), object(4)
memory usage: 420.8+ KB

In [8]:
object_columns = list(sh_relevant.select_dtypes(['object']).columns)
object_columns

['Thương hiệu', 'Ngành hàng', 'Sản phẩm', 'Ghi chú']

In [9]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_relevant[column].unique()), "unique values", "\t & \t", 
          sh_relevant[column].notnull().sum(), "non-null values\t", 
          round(100* sh_relevant[column].notnull().sum()/len(sh_relevant[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 3590 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 3590 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
275 unique values 	 & 	 3590 non-null values	 100.0 % non-null
*, Column:  Ghi chú
5 unique values 	 & 	 4 non-null values	 0.11 % non-null

In [10]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_relevant[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        947
Nutifood        396
Nutricare       392
TH True Milk    375
Vitadairy       290
Nestlé          268
FCV             190
IDP             152
Mead Johnson    130
Abbott          108
Vinasoy          70
Đà Lạt Milk      62
Fonterra         54
Hipp             54
Betagen          42
Yakult           36
Hoff             24
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       1367
SN        599
SC        464
BRAND     285
NGK       232
SĐN       209
SĐ        124
KEM       106
BAD        72
BDD        50
ĐƯỜNG      19
BƠ         18
PM         16
Kem        12
FOOD       12
TUNL        5
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
Vinamilk Susu             19
ColosBaby                 19
Thương hiệu Abbott        18
Vinamilk Yomilk           18
Varna                     18
                          ..
GrandCare                  1
Nuvi Rau củ                1
Colos Gain                 1
Sữa non Colos Baby         1
Sữa tươi lúa mạch Nuvi     1
Name: Sản phẩm, Length: 275, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
yes, minigame, fanpage                1
#DinhDuongChatLuong #ViConLaSo1       1
#VềNhàĐónVuLan và  #VuiSongMoiNgay    1
campaign Bé Lành Học Nhanh            1
Name: Ghi chú, dtype: int64
----------------------------------------------------------------------------------------------------

Sheet Channel

In [11]:
sh_channel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3589 entries, 0 to 3588
Data columns (total 36 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Thương hiệu                   3589 non-null   object
 1   Ngành hàng                    3589 non-null   object
 2   Sản phẩm                      3589 non-null   object
 3   Thời gian                     3589 non-null   datetime64[ns]
 4   Fanpage                       2157 non-null   float64
 5   FB page                       3064 non-null   float64
 6   FB user                       3124 non-null   float64
 7   FB group                      3091 non-null   float64
 8   Tiktok                        1820 non-null   float64
 9   Forum                         737 non-null    float64
 10  News                          1128 non-null   float64
 11  Youtube                       915 non-null    float64
 12  E-commerce                    249 non-null    float64
 13  Instagram                     47 non-null     float64
 14  Threads                       117 non-null    float64
 15  Linkedin                      49 non-null     float64
 16  Total after                   3589 non-null   int64
 17  Total                         3589 non-null   float64
 18  Total FB và Total FB, Tiktok  3589 non-null   float64
 19  Buzzes thêm                   283 non-null    float64
 20  Fanpage new                   3563 non-null   float64
 21  FB page new                   3563 non-null   float64
 22  FB user new                   3563 non-null   float64
 23  FB group new                  3563 non-null   float64
 24  Tiktok new                    3585 non-null   float64
 25  Forum new                     3589 non-null   int64
 26  News new                      3589 non-null   int64
 27  Youtube new                   3589 non-null   int64
 28  E-commerce new                3589 non-null   int64
 29  Instagram new                 3589 non-null   int64
 30  Threads new                   3589 non-null   int64
 31  Linkedin new                  3589 non-null   int64
 32  Total new                     3589 non-null   float64
 33  Check Total Buzz              3589 non-null   int64
 34  Total Facebook                3589 non-null   float64
 35  Ghi chú                       5 non-null      object
dtypes: datetime64[ns](1), float64(22), int64(9), object(4)
memory usage: 1009.5+ KB

In [12]:
object_columns = list(sh_channel.select_dtypes(['object']).columns)
object_columns

['Thương hiệu', 'Ngành hàng', 'Sản phẩm', 'Ghi chú']

In [13]:
# Đếm số lượng giá trị duy nhất cho mỗi cột
for column in object_columns: 
    print("*, Column: ", column)   
    print(len(sh_channel[column].unique()), "unique values", "\t & \t", 
          sh_channel[column].notnull().sum(), "non-null values\t", 
          round(100* sh_channel[column].notnull().sum()/len(sh_channel[column]),2), 
          "% non-null")

*, Column:  Thương hiệu
17 unique values 	 & 	 3589 non-null values	 100.0 % non-null
*, Column:  Ngành hàng
16 unique values 	 & 	 3589 non-null values	 100.0 % non-null
*, Column:  Sản phẩm
274 unique values 	 & 	 3589 non-null values	 100.0 % non-null
*, Column:  Ghi chú
6 unique values 	 & 	 5 non-null values	 0.14 % non-null

In [14]:
for column in object_columns:
    print('-'*100)
    print("*, Column: ", column)
    print(sh_sentiment[column].value_counts())
    print('-'*100)

----------------------------------------------------------------------------------------------------
*, Column:  Thương hiệu
Vinamilk        4108
TH True Milk    1749
Nutifood        1636
Nutricare       1388
Vitadairy       1328
Nestlé          1205
FCV              833
IDP              685
Mead Johnson     586
Abbott           534
Vinasoy          324
Đà Lạt Milk      287
Hipp             267
Fonterra         253
Yakult           178
Betagen          172
Hoff             112
Name: Thương hiệu, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ngành hàng
SB       5752
SN       2764
SC       2124
BRAND    1319
NGK       938
SĐN       893
SĐ        544
KEM       513
BAD       306
BDD       189
BƠ         85
PM         68
ĐƯỜNG      61
FOOD       54
Brand      30
TUNL        5
Name: Ngành hàng, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Sản phẩm
ColosBaby               93
Vinamilk 100%           91
Vinamilk Fino           89
Sữa bột Hipp            89
Thương hiệu Nutifood    89
                        ..
Sữa non Colos Baby       1
Nunest Kid               1
GrandCare                1
Leanmax Colostrum        1
Vinamilk Platinum        1
Name: Sản phẩm, Length: 274, dtype: int64
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
*, Column:  Ghi chú
rao vặt                                                                                                                                                                                         59
minigame trên fanpage                                                                                                                                                                           14
không lấy shares ảo                                                                                                                                                                              7
rao vặt sản phẩm                                                                                                                                                                                 6
#NutifoodThuyDien #Varna #Thanhxuanmaichay #khuyenmai                                                                                                                                            5
                                                                                                                                                                                                ..
minigame "Đáp trúng, nhận quà" trên fanpge Lazada Super Moms                                                                                                                                     1
minigame trên fanpage Nestlé Mom&Me Vietnam http://facebook.com/159267667447549_796314005515379 và  livestream trên fanpage KidsPlaza.vn http://facebook.com/159267667447549_796314005515379     1
minigame trên fanpage Nestlé Mom&Me Vietnam http://facebook.com/400564340152929_699671105531096                                                                                                  1
các bài review sản phẩm từ mẹ bỉm                                                                                                                                                                1
3000 Positive FBuser Công dụng Vinamilk 100% - 1 Lít Không Đường                                                                                                                                 1
Name: Ghi chú, Length: 292, dtype: int64
----------------------------------------------------------------------------------------------------

# Tổng quan

In [15]:
month = "06/2024"
year = "2024"

pre_month = "06/2023"
pre_ytd = ['01/2023','02/2023','03/2023','04/2023','05/2023','06/2023']
pre_year = "2023"

In [16]:
exclude_brands = ["Hoff", "Betagen", "Yakult"]
bdd = ['BAD', 'BDD']

In [17]:
#Thị phần ngành sữa theo Tháng năm 2024
filtered_sh_sentiment_mon = sh_sentiment[(sh_sentiment["Thời gian"] == month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV = filtered_sh_sentiment_mon.groupby(["Thương hiệu"]).agg({"Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
SOV

     Thương hiệu  Total new
0       Vinamilk   954176.0
1         Abbott   704597.0
2       Nutifood   612156.0
3         Nestlé   404083.0
4      Vitadairy    87055.0
5   TH True Milk    86406.0
6        Vinasoy    74609.0
7            IDP    54822.0
8            FCV    46819.0
9   Mead Johnson    20913.0
10          Hipp    15043.0
11      Fonterra    11533.0
12     Nutricare    11429.0
13   Đà Lạt Milk     5679.0

In [18]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl') as writer:
    SOV.to_excel(writer, index=False, sheet_name='month_brand')

In [19]:
#Thị phần ngành sữa theo tháng năm 2023

filtered_sh_sentiment_pre_mon = sh_sentiment[(sh_sentiment["Thời gian"] == pre_month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
SOV_pre = filtered_sh_sentiment_pre_mon.groupby(["Thương hiệu"]).agg({"Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
SOV_pre

     Thương hiệu  Total new
0       Vinamilk   351706.0
1         Nestlé   322594.0
2       Nutifood    84670.0
3         Abbott    79531.0
4   Mead Johnson    30593.0
5   TH True Milk    26190.0
6            FCV    24991.0
7            IDP    23784.0
8      Vitadairy    22449.0
9        Vinasoy     6661.0
10      Fonterra     3184.0
11          Hipp      727.0
12   Đà Lạt Milk      512.0

In [20]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    SOV_pre.to_excel(writer, index=False, sheet_name='pre-month_brand')

In [21]:
#Sentiment các brand theo Tháng năm 2024
filtered_sh_sentiment_mon = sh_sentiment[(sh_sentiment["Thời gian"] == month) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
brand_sent = filtered_sh_sentiment_mon.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
brand_sent

     Thương hiệu  Positive new  Neutral new  Negative new  Total new
0       Vinamilk      734489.0     219370.0         317.0   954176.0
1         Abbott      444525.0     259752.0         321.0   704597.0
2       Nutifood      590886.0      21259.0          10.0   612156.0
3         Nestlé      372389.0      31574.0         120.0   404083.0
4      Vitadairy       36087.0      50941.0          27.0    87055.0
5   TH True Milk       18746.0      67543.0         117.0    86406.0
6        Vinasoy       56953.0      17644.0          12.0    74609.0
7            IDP       25105.0      29622.0          95.0    54822.0
8            FCV       12240.0      34509.0          69.0    46819.0
9   Mead Johnson        6095.0      14721.0          97.0    20913.0
10          Hipp        2893.0      12057.0          93.0    15043.0
11      Fonterra        7308.0       4225.0           0.0    11533.0
12     Nutricare        2056.0       9364.0           9.0    11429.0
13   Đà Lạt Milk         134.0       5543.0           2.0     5679.0

In [22]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    brand_sent.to_excel(writer, index=False, sheet_name='month_brand_sent')

In [23]:
#Sắc thái thảo luận của các thương hiệu pre-YTD
filtered_sh_sentiment_pre_ytd = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
sent_pre_ytd = filtered_sh_sentiment_pre_ytd.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
sent_pre_ytd

     Thương hiệu  Positive new  Neutral new  Negative new  Total new
0       Vinamilk     1551209.0     219717.0        2208.0  1773134.0
1         Nestlé      686919.0      61214.0         572.0   748705.0
2         Abbott      293170.0     307427.0        1616.0   602213.0
3       Nutifood      371174.0      28563.0         216.0   399953.0
4            FCV      261358.0     115894.0         149.0   377402.0
5   Mead Johnson      102430.0      17858.0         379.0   120666.0
6            IDP       55895.0      60906.0         406.0   117208.0
7   TH True Milk       31179.0      69037.0         364.0   100580.0
8        Vinasoy       56656.0      30914.0        3587.0    91156.0
9      Vitadairy       30510.0      32952.0         464.0    63927.0
10      Fonterra        3892.0       4051.0          14.0     7957.0
11          Hipp        1172.0       2967.0          43.0     4182.0
12   Đà Lạt Milk         701.0       2205.0           8.0     2914.0

In [24]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    sent_pre_ytd.to_excel(writer, index=False, sheet_name='pre-YTD-sent')

In [45]:
#Category_pre-YTD
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].isin(pre_ytd) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands))]
cate = filtered_sh_sentiment.pivot_table(index='Thương hiệu', columns='Ngành hàng', values='Total new', aggfunc='sum').round(decimals=0).fillna(0)
cate['Total'] = cate.sum(axis=1)
cate = cate.sort_values(by="Total",ascending=False)
cate.reset_index(inplace=True)
# cate['BDD'] = cate[['BDD','BAD']].sum(axis=1)
# cate['Khác'] = cate['Total'] - cate[['SN','SC','SB','BDD','SĐ','SĐN']].sum(axis=1)
# cate = cate[['Thương hiệu','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']]
# cate

KeyError: "None of [Index(['BDD', 'BAD'], dtype='object', name='Ngành hàng')] are in the [columns]"

In [25]:
#Số buzz theo tuần
filtered_sh_sentiment = sh_sentiment[((sh_sentiment["Thời gian"] == month)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
week = filtered_sh_sentiment.pivot_table(index='Tuần', columns='Thương hiệu', values='Total new', aggfunc='sum').round(decimals=0)
column_sums = week.sum(axis=0, numeric_only=True)
week.loc['Total'] = week.sum(numeric_only=True)
week.reset_index(inplace=True)
total_values = week.loc[week['Tuần'] == 'Total'].drop(columns=['Tuần']).iloc[0]
sorted_columns = total_values.sort_values(ascending=False).index
sorted_columns = ['Tuần'] + sorted_columns.tolist()
week = week[sorted_columns]
week

Thương hiệu,Tuần,Vinamilk,Abbott,Nutifood,Nestlé,Vitadairy,TH True Milk,Vinasoy,IDP,FCV,Mead Johnson,Hipp,Fonterra,Nutricare,Đà Lạt Milk
0,01/06/2024 - 07/06/2024,106196.0,245841.0,50041.0,39893.0,18192.0,38802.0,58465.0,12947.0,4306.0,4437.0,2818.0,2381.0,2285.0,1077.0
1,08/06/2024 - 14/06/2024,141664.0,65970.0,92048.0,33288.0,20860.0,16416.0,7316.0,9688.0,5134.0,5165.0,3443.0,4878.0,2813.0,1601.0
2,15/06/2024 - 21/06/2024,318525.0,120104.0,448709.0,121374.0,22242.0,15583.0,2068.0,9810.0,5308.0,3972.0,3242.0,2841.0,2831.0,1430.0
3,22/06/2024 - 28/06/2024,238393.0,193375.0,17891.0,121214.0,21976.0,12779.0,3982.0,16126.0,15376.0,6420.0,4539.0,1149.0,2993.0,1435.0
4,29/06/2024 - 30/06/2024,149398.0,79307.0,3467.0,88314.0,3785.0,2826.0,2778.0,6251.0,16695.0,919.0,1001.0,284.0,507.0,136.0
5,Total,954176.0,704597.0,612156.0,404083.0,87055.0,86406.0,74609.0,54822.0,46819.0,20913.0,15043.0,11533.0,11429.0,5679.0

In [26]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    week.to_excel(writer, index=False, sheet_name='week')

In [27]:
sh_relevant["Thời gian"] = sh_relevant["Thời gian"].astype(str)
sh_sentiment["Thời gian"] = sh_sentiment["Thời gian"].astype(str)
sh_channel["Thời gian"] = sh_channel["Thời gian"].astype(str)

In [28]:
#Sắc thái thảo luận của các thương hiệu YTD
filtered_sh_sentiment_YTD = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False)) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands)]
sentiment_brand = filtered_sh_sentiment_YTD.groupby(["Thương hiệu"]).agg({"Positive new": "sum","Neutral new": "sum","Negative new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
sentiment_brand

     Thương hiệu  Positive new  Neutral new  Negative new  Total new
0       Vinamilk     4198483.0    1303370.0        1237.0  5503090.0
1         Nestlé     3030287.0     178895.0         359.0  3209541.0
2       Nutifood     2625424.0     124749.0         491.0  2750664.0
3         Abbott      712344.0     470560.0       14146.0  1197049.0
4            IDP      877449.0     122931.0        4595.0  1004974.0
5   TH True Milk       47454.0     292752.0        1733.0   341939.0
6            FCV       53787.0     218176.0         465.0   272428.0
7   Mead Johnson      177880.0      84769.0         526.0   263176.0
8      Vitadairy       98576.0     151409.0         222.0   250207.0
9       Fonterra      122263.0      73062.0          70.0   195394.0
10       Vinasoy       87908.0      60506.0         223.0   148637.0
11          Hipp       16823.0      60540.0         151.0    77514.0
12     Nutricare        7019.0      40753.0          54.0    47826.0
13   Đà Lạt Milk         638.0      18681.0          11.0    19330.0

In [29]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    sentiment_brand.to_excel(writer, index=False, sheet_name='YTD-sent')

In [30]:
#Category
filtered_sh_sentiment = sh_sentiment[(sh_sentiment["Thời gian"].str.contains(year,na=False) & ~sh_sentiment["Thương hiệu"].isin(exclude_brands))]
cate = filtered_sh_sentiment.pivot_table(index='Thương hiệu', columns='Ngành hàng', values='Total new', aggfunc='sum').round(decimals=0).fillna(0)
cate['Total'] = cate.sum(axis=1)
cate = cate.sort_values(by="Total",ascending=False)
cate.reset_index(inplace=True)
cate['BDD'] = cate[['BDD','BAD']].sum(axis=1)
cate['Khác'] = cate['Total'] - cate[['SN','SC','SB','BDD','SĐ','SĐN']].sum(axis=1)
cate = cate[['Thương hiệu','SN','SC','SB','BDD','SĐ','SĐN','Khác','Total']]
cate

Ngành hàng,Thương hiệu,SN,SC,SB,BDD,SĐ,SĐN,Khác,Total
0,Vinamilk,376279.0,2656971.0,1857046.0,7454.0,415944.0,16915.0,172481.0,5503090.0
1,Nestlé,1647270.0,4312.0,1327315.0,8249.0,0.0,0.0,222395.0,3209541.0
2,Nutifood,26558.0,2863.0,2691612.0,207.0,779.0,1373.0,27272.0,2750664.0
3,Abbott,0.0,0.0,1180343.0,0.0,0.0,0.0,16706.0,1197049.0
4,IDP,993639.0,8534.0,0.0,0.0,0.0,0.0,2801.0,1004974.0
5,TH True Milk,69795.0,37326.0,17994.0,0.0,0.0,8152.0,208672.0,341939.0
6,FCV,54528.0,173885.0,35872.0,0.0,7302.0,0.0,841.0,272428.0
7,Mead Johnson,0.0,0.0,262243.0,0.0,0.0,0.0,933.0,263176.0
8,Vitadairy,21005.0,0.0,199467.0,0.0,0.0,0.0,29735.0,250207.0
9,Fonterra,0.0,0.0,195160.0,0.0,0.0,0.0,234.0,195394.0
10,Vinasoy,0.0,4832.0,0.0,0.0,0.0,140025.0,3780.0,148637.0
11,Hipp,0.0,0.0,52114.0,7679.0,0.0,0.0,17721.0,77514.0
12,Nutricare,2795.0,605.0,33998.0,202.0,0.0,111.0,10115.0,47826.0
13,Đà Lạt Milk,15189.0,2401.0,0.0,0.0,0.0,0.0,1740.0,19330.0

In [31]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl',mode='a') as writer:
    cate.to_excel(writer, index=False, sheet_name='YTD-Cate')

In [32]:
#Relevant thảo luận của các thương hiệu YTD
filtered_sh_relevant_YTD = sh_relevant[(sh_relevant["Thời gian"].str.contains(year,na=False)) & ~sh_relevant["Thương hiệu"].isin(exclude_brands)]
relevant_brand = filtered_sh_relevant_YTD.groupby(["Thương hiệu"]).agg({"Relevant new": "sum","Irrelevant new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()
relevant_brand

     Thương hiệu  Relevant new  Irrelevant new  Total new
0       Vinamilk     5155569.0        347521.0  5503090.0
1         Nestlé     3197756.0         11785.0  3209541.0
2       Nutifood     2720790.0         29874.0  2750664.0
3         Abbott     1089209.0        107840.0  1197049.0
4            IDP      988657.0         16317.0  1004974.0
5   TH True Milk      280137.0         61802.0   341939.0
6            FCV      255175.0         17253.0   272428.0
7   Mead Johnson      248135.0         15041.0   263176.0
8      Vitadairy      239578.0         10629.0   250207.0
9       Fonterra      172704.0         22690.0   195394.0
10       Vinasoy      137892.0         10745.0   148637.0
11          Hipp       67155.0         10359.0    77514.0
12     Nutricare       45216.0          2610.0    47826.0
13   Đà Lạt Milk       19228.0           102.0    19330.0

In [33]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    relevant_brand.to_excel(writer, index=False, sheet_name='YTD-rlv')

In [34]:
# Thảo luận của các thương hiệu theo kênh YTD
filtered_sh_channel_YTD = sh_channel[(sh_channel["Thời gian"].str.contains(year,na=False)) & ~sh_channel["Thương hiệu"].isin(exclude_brands)]
channel_brand = filtered_sh_channel_YTD.groupby(["Thương hiệu"]).agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()  
channel_brand["Khác"] = channel_brand["Total new"] - channel_brand.drop(columns=["Thương hiệu", "Total new"]).sum(axis=1)
channel_brand = channel_brand[['Thương hiệu','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
channel_brand

,Thương hiệu,Fanpage new,FB page new,FB user new,FB group new,Tiktok new,Forum new,News new,Youtube new,Khác,Total new
0,Vinamilk,549716.0,1230122.0,3046321.0,442310.0,197849.0,12127,10775,12495,1375.0,5503090.0
1,Nestlé,177254.0,1266795.0,1380289.0,363641.0,19107.0,210,1243,146,856.0,3209541.0
2,Nutifood,1917979.0,151177.0,465141.0,190585.0,23675.0,21,572,365,1149.0,2750664.0
3,Abbott,372113.0,262972.0,367737.0,178923.0,14727.0,304,194,71,8.0,1197049.0
4,IDP,168460.0,79898.0,432692.0,30082.0,285355.0,105,487,6988,907.0,1004974.0
5,TH True Milk,55310.0,138440.0,61455.0,66239.0,17092.0,326,1675,1336,66.0,341939.0
6,FCV,29425.0,105372.0,41862.0,64256.0,30882.0,68,133,394,36.0,272428.0
7,Mead Johnson,883.0,148884.0,33205.0,74733.0,5096.0,67,102,58,148.0,263176.0
8,Vitadairy,25043.0,48575.0,93238.0,73545.0,9053.0,45,92,257,359.0,250207.0
9,Fonterra,12368.0,97781.0,76850.0,3073.0,5231.0,6,49,34,2.0,195394.0
10,Vinasoy,90632.0,16118.0,26301.0,13269.0,1842.0,13,222,223,17.0,148637.0
11,Hipp,295.0,23493.0,6791.0,44559.0,2105.0,25,2,10,234.0,77514.0
12,Nutricare,3982.0,5036.0,19177.0,13359.0,5985.0,0,81,135,71.0,47826.0
13,Đà Lạt Milk,301.0,3426.0,6495.0,8402.0,488.0,18,85,43,72.0,19330.0

In [35]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    channel_brand.to_excel(writer, index=False, sheet_name='YTD-chn')

# Ngành hàng

Sentiment, Relevant

In [36]:
def process_data(df, columns, nganh_hang, year):
    filtered_df = df[(df["Ngành hàng"] == nganh_hang) & (df["Thời gian"].str.contains(year, na=False))]
    
    grouped_df = filtered_df.groupby(["Sản phẩm"]).agg(columns).sort_values(by="Total new", ascending=False).reset_index().round()
    
    top_13 = grouped_df.head(13)
    khac = grouped_df.iloc[13:].agg(columns).to_frame().transpose()
    
    result_df = pd.concat([top_13, khac], ignore_index=True)
    result_df.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
    
    return result_df


# Define columns for Sentiment
sentiment_columns = { "Total new": "sum", "Positive new": "sum", "Neutral new": "sum", "Negative new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx"
existing_excel = pd.ExcelFile(existing_excel_path)

# Create Excel writer
with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a') as writer:
    for nganh_hang in nganh_hang_list:
        sentiment_data = process_data(sh_sentiment, sentiment_columns, nganh_hang, year)
        
        # Display the sentiment_data
        print(f"Sentiment ({nganh_hang}):")
        print(sentiment_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        sheet_name = f"Sentiment_{nganh_hang}"
        sentiment_data.to_excel(writer, sheet_name=sheet_name, index=False)

# Close the existing Excel file
existing_excel.close()


# Define columns for Relevant
relevant_columns = {"Relevant new": "sum","Irrelevant new": "sum","Total new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx"
existing_excel = pd.ExcelFile(existing_excel_path)

# Create Excel writer
with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a') as writer:
    for nganh_hang in nganh_hang_list:
        relevant_data = process_data(sh_relevant, relevant_columns, nganh_hang, year)
        
        # Display the sentiment_data
        print(f"Relevant ({nganh_hang}):")
        print(relevant_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        sheet_name = f"Relevant_{nganh_hang}"
        relevant_data.to_excel(writer, sheet_name=sheet_name, index=False)

# Close the existing Excel file
existing_excel.close()

Sentiment (SC):
                     Sản phẩm  Total new  Positive new  Neutral new  \
0           Sữa chua Vinamilk   842255.0      711172.0     130955.0
1              Vinamilk Probi   640579.0      561081.0      79357.0
2               Vinamilk Susu   588750.0      499568.0      89123.0
3               Vinamilk Hero   583996.0      498687.0      85308.0
4                      Yomost   167058.0       32571.0     134475.0
5             Sữa chua Yakult    39442.0       10674.0      28663.0
6              TH True Yogurt    30376.0        3724.0      26485.0
7               Sữa chua Hoff    22976.0         702.0      22003.0
8             Sữa chua TOPKID     5614.0         919.0       4653.0
9                        Veyo     4832.0        3450.0       1381.0
10  Sữa chua uống Nestle Yogu     4120.0           8.0       4112.0
11      Sữa chua uống LIF KUN     4092.0         352.0       3722.0
12                 SC Betagen     3990.0        1998.0       1985.0
13              Sản phẩm khác    20588.0        2105.0      18475.0

    Negative new
0          128.0
1          141.0
2           59.0
3            1.0
4           11.0
5          105.0
6          167.0
7          271.0
8           41.0
9            1.0
10           0.0
11          18.0
12           7.0
13           6.0

==================================================

Sentiment (SN):
                     Sản phẩm  Total new  Positive new  Neutral new  \
0                        Milo  1639867.0     1613374.0      26318.0
1                     LOF KUN   928787.0      830808.0      93914.0
2               Vinamilk 100%   273632.0      242698.0      30928.0
3         Vinamilk Green Farm    60323.0       48149.0      12166.0
4      Sữa lúa mạch Lof Malto    51430.0       38921.0      12205.0
5       Sữa tươi TH True Milk    38246.0        6838.0      31030.0
6   Sữa tươi Dutch Lady (RTD)    34419.0        2152.0      32223.0
7                    Ovaltine    20107.0       14339.0       5727.0
8               Vinamilk Fino    19443.0        8101.0      11249.0
9        Sữa tươi Đà Lạt Milk    15189.0         464.0      14716.0
10            Sữa tươi TOPKID    12466.0        3219.0       9226.0
11   Sữa non Colos Fresh Milk    12122.0        9328.0       2794.0
12               TH True HILO    10873.0        3160.0       7608.0
13              Sản phẩm khác    90154.0       17312.0      72430.0

    Negative new
0          175.0
1         4065.0
2            6.0
3            8.0
4          304.0
5          378.0
6           45.0
7           42.0
8           93.0
9            9.0
10          22.0
11           0.0
12         105.0
13         412.0

==================================================

Sentiment (SB):
                     Sản phẩm  Total new  Positive new  Neutral new  \
0                   Nuvi Grow  1837419.0     1825112.0      12303.0
1                   Grow Plus   822064.0      776148.0      45730.0
2   Vinamilk Dielac Grow Plus   782181.0      388011.0     394157.0
3               Nan Optipro 4   535012.0      524043.0      10967.0
4         Abbott Grow Vietnam   479708.0      285360.0     193849.0
5          Vinamilk Yoko Gold   389871.0      376625.0      13226.0
6               S-26 Ultima 3   299244.0      251692.0      47505.0
7           Pediasure Vietnam   296194.0      204532.0      90982.0
8             Similac Vietnam   287664.0      173080.0     113551.0
9            Vinamilk Optimum   242077.0      214503.0      27406.0
10                        Nan   228835.0      176046.0      52727.0
11      Vinamilk Sure Prevent   216872.0      205737.0      11132.0
12                EnfaGrow A+   194580.0      161803.0      32660.0
13              Sản phẩm khác  1241443.0      732055.0     497177.0

    Negative new
0            4.0
1          186.0
2           13.0
3            2.0
4          499.0
5           20.0
6           48.0
7          680.0
8         1034.0
9          168.0
10          62.0
11           3.0
12         117.0
13       12210.0

==================================================

Sentiment (SĐ):
                        Sản phẩm  Total new  Positive new  Neutral new  \
0               Vinamilk Ông thọ   391609.0      189094.0     202408.0
1   Vinamilk Ngôi Sao Phương Nam    15615.0        3447.0      12166.0
2             Sữa đặc Dutch Lady     7073.0         163.0       6910.0
3               Sữa đặc Vinamilk     5982.0          20.0       5962.0
4               Vinamilk Tài lộc     2738.0          55.0       2681.0
5               Sữa đặc Nutifood      779.0           0.0        779.0
6               Sữa đặc Hoàn Hảo      229.0           1.0        228.0
7                            NaN        0.0           0.0          0.0
13                 Sản phẩm khác        NaN           NaN          NaN

    Negative new
0          107.0
1            2.0
2            0.0
3            0.0
4            2.0
5            0.0
6            0.0
7            0.0
13           NaN

==================================================

Sentiment (SĐN):
                    Sản phẩm  Total new  Positive new  Neutral new  \
0                       Fami   139977.0       84208.0      55547.0
1                TH True Nut     7106.0        1988.0       5049.0
2        Vinamilk Hạt Óc Chó     4727.0        1545.0       3148.0
3         Vinamilk Super Nut     4103.0         439.0       3655.0
4         Vinamilk Hạnh Nhân     2807.0        1404.0       1400.0
5            Vinamilk Đậu Đỏ     2802.0        1405.0       1395.0
6      Sữa Đậu Nành Vinamilk     1985.0         981.0       1003.0
7      Sữa đậu nành Nutifood     1373.0          21.0       1352.0
8         TH True Light Meal      872.0         201.0        654.0
9   Vinamilk Sữa hạt Cao Đạm      462.0          67.0        395.0
10               TH true OAT      174.0          80.0         94.0
11             Nunut Lục Bảo      111.0           0.0        111.0
12      Sữa đậu nành Vinasoy       48.0           6.0         42.0
13             Sản phẩm khác       29.0           3.0         26.0

    Negative new
0          222.0
1           69.0
2           34.0
3            9.0
4            3.0
5            2.0
6            1.0
7            0.0
8           17.0
9            0.0
10           0.0
11           0.0
12           0.0
13           0.0

==================================================

Relevant (SC):
                     Sản phẩm  Relevant new  Irrelevant new  Total new
0           Sữa chua Vinamilk      803891.0         38364.0   842255.0
1              Vinamilk Probi      591791.0         48788.0   640579.0
2               Vinamilk Susu      535012.0         53738.0   588750.0
3               Vinamilk Hero      530478.0         53518.0   583996.0
4                      Yomost      161116.0          5942.0   167058.0
5             Sữa chua Yakult       34963.0          4479.0    39442.0
6              TH True Yogurt       27483.0          2893.0    30376.0
7               Sữa chua Hoff       21274.0          1702.0    22976.0
8             Sữa chua TOPKID        5556.0            58.0     5614.0
9                        Veyo        4160.0           672.0     4832.0
10  Sữa chua uống Nestle Yogu        4120.0             0.0     4120.0
11      Sữa chua uống LIF KUN        4085.0             7.0     4092.0
12                 SC Betagen        3627.0           363.0     3990.0
13              Sản phẩm khác       19505.0          1083.0    20588.0

==================================================

Relevant (SN):
                     Sản phẩm  Relevant new  Irrelevant new  Total new
0                        Milo     1632192.0          7675.0  1639867.0
1                     LOF KUN      916491.0         12296.0   928787.0
2               Vinamilk 100%      257890.0         15742.0   273632.0
3         Vinamilk Green Farm       56894.0          3429.0    60323.0
4      Sữa lúa mạch Lof Malto       49084.0          2346.0    51430.0
5       Sữa tươi TH True Milk       37995.0           251.0    38246.0
6   Sữa tươi Dutch Lady (RTD)       29558.0          4861.0    34419.0
7                    Ovaltine       17919.0          2188.0    20107.0
8               Vinamilk Fino       18202.0          1241.0    19443.0
9        Sữa tươi Đà Lạt Milk       15115.0            74.0    15189.0
10            Sữa tươi TOPKID       12428.0            38.0    12466.0
11   Sữa non Colos Fresh Milk       12063.0            59.0    12122.0
12               TH True HILO       10726.0           147.0    10873.0
13              Sản phẩm khác       86233.0          3921.0    90154.0

==================================================

Relevant (SB):
                     Sản phẩm  Relevant new  Irrelevant new  Total new
0                   Nuvi Grow     1825894.0         11525.0  1837419.0
1                   Grow Plus      807448.0         14616.0   822064.0
2   Vinamilk Dielac Grow Plus      729111.0         53070.0   782181.0
3               Nan Optipro 4      532624.0          2388.0   535012.0
4         Abbott Grow Vietnam      444021.0         35687.0   479708.0
5          Vinamilk Yoko Gold      382780.0          7091.0   389871.0
6               S-26 Ultima 3      298957.0           287.0   299244.0
7           Pediasure Vietnam      274942.0         21252.0   296194.0
8             Similac Vietnam      251515.0         36149.0   287664.0
9            Vinamilk Optimum      237746.0          4331.0   242077.0
10                        Nan      228525.0           310.0   228835.0
11      Vinamilk Sure Prevent      211315.0          5557.0   216872.0
12                EnfaGrow A+      182019.0         12561.0   194580.0
13              Sản phẩm khác     1149280.0         92163.0  1241443.0

==================================================

Relevant (SĐ):
                        Sản phẩm  Relevant new  Irrelevant new  Total new
0               Vinamilk Ông thọ      365714.0         25895.0   391609.0
1   Vinamilk Ngôi Sao Phương Nam       14894.0           721.0    15615.0
2             Sữa đặc Dutch Lady        7073.0             0.0     7073.0
3               Sữa đặc Vinamilk        5936.0            46.0     5982.0
4               Vinamilk Tài lộc        2720.0            18.0     2738.0
5               Sữa đặc Nutifood         779.0             0.0      779.0
6               Sữa đặc Hoàn Hảo         229.0             0.0      229.0
7                            NaN           0.0             0.0        0.0
13                 Sản phẩm khác           NaN             NaN        NaN

==================================================

Relevant (SĐN):
                    Sản phẩm  Relevant new  Irrelevant new  Total new
0                       Fami      130526.0          9451.0   139977.0
1                TH True Nut        7057.0            49.0     7106.0
2        Vinamilk Hạt Óc Chó        4293.0           434.0     4727.0
3         Vinamilk Super Nut        3957.0           146.0     4103.0
4         Vinamilk Hạnh Nhân        2465.0           342.0     2807.0
5            Vinamilk Đậu Đỏ        2460.0           342.0     2802.0
6      Sữa Đậu Nành Vinamilk        1389.0           596.0     1985.0
7      Sữa đậu nành Nutifood        1373.0             0.0     1373.0
8         TH True Light Meal         853.0            19.0      872.0
9   Vinamilk Sữa hạt Cao Đạm         446.0            16.0      462.0
10               TH true OAT         174.0             0.0      174.0
11             Nunut Lục Bảo         111.0             0.0      111.0
12      Sữa đậu nành Vinasoy          48.0             0.0       48.0
13             Sản phẩm khác          29.0             0.0       29.0

==================================================

In [37]:
#Sentiment BDD

filtered_sh_sentiment_BDD = sh_sentiment[(sh_sentiment["Ngành hàng"].isin(bdd)) & (sh_sentiment["Thời gian"].str.contains(year, na=False))]
sentiment_BDD = filtered_sh_sentiment_BDD.groupby(["Sản phẩm"]).agg(sentiment_columns).sort_values(by="Total new", ascending=False).reset_index().round()
sentiment_BDD["Khác"] = sentiment_BDD["Total new"] - sentiment_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

sentiment_BDD_top_13 = sentiment_BDD.head(13)

SP_khac = sentiment_BDD.iloc[13:].agg(sentiment_columns).to_frame().transpose()
    
sentiment_BDD = pd.concat([sentiment_BDD_top_13, SP_khac], ignore_index=True)
sentiment_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
sentiment_BDD.loc[13, 'Khác'] = sentiment_BDD.loc[13, 'Total new']
sentiment_BDD

,Sản phẩm,Total new,Positive new,Neutral new,Negative new,Khác
0,Gerber,8126.0,289.0,7837.0,0.0,0.0
1,Bột ăn dặm Hipp,7679.0,565.0,7099.0,15.0,0.0
2,Vinamilk Ridielac,6742.0,2344.0,4395.0,3.0,0.0
3,Bột Dinh Dưỡng Vinamilk,617.0,126.0,491.0,0.0,0.0
4,Bột ăn dặm Nuti IQ,207.0,156.0,51.0,0.0,0.0
5,Bột ăn dặm Metacare,202.0,33.0,169.0,0.0,0.0
6,Cerelac,123.0,27.0,96.0,0.0,0.0
7,Bột ăn dặm Vinamilk Optimum Gold,94.0,2.0,92.0,0.0,0.0
8,Bột ăn dặm Vinamilk Organic Gold,1.0,0.0,1.0,0.0,0.0
9,NaN,0.0,0.0,0.0,0.0,NaN
13,Sản phẩm khác,NaN,NaN,NaN,NaN,NaN

In [38]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    sentiment_BDD.to_excel(writer, index=False, sheet_name='Sentiment BDD')

In [39]:
#Relevant BDD

filtered_sh_relevant_BDD = sh_relevant[(sh_relevant["Ngành hàng"].isin(bdd)) & (sh_relevant["Thời gian"].str.contains(year, na=False))]
relevant_BDD = filtered_sh_relevant_BDD.groupby(["Sản phẩm"]).agg(relevant_columns).sort_values(by="Total new", ascending=False).reset_index().round()
relevant_BDD["Khác"] = relevant_BDD["Total new"] - relevant_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

relevant_BDD_top_13 = relevant_BDD.head(13)

SP_khac = relevant_BDD.iloc[13:].agg(relevant_columns).to_frame().transpose()
    
relevant_BDD = pd.concat([relevant_BDD_top_13, SP_khac], ignore_index=True)
relevant_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
relevant_BDD.loc[13, 'Khác'] = relevant_BDD.loc[13, 'Total new']
relevant_BDD

,Sản phẩm,Relevant new,Irrelevant new,Total new,Khác
0,Gerber,8126.0,0.0,8126.0,0.0
1,Bột ăn dặm Hipp,7394.0,285.0,7679.0,0.0
2,Vinamilk Ridielac,6517.0,225.0,6742.0,0.0
3,Bột Dinh Dưỡng Vinamilk,617.0,0.0,617.0,0.0
4,Bột ăn dặm Nuti IQ,207.0,0.0,207.0,0.0
5,Bột ăn dặm Metacare,201.0,1.0,202.0,0.0
6,Cerelac,123.0,0.0,123.0,0.0
7,Bột ăn dặm Vinamilk Optimum Gold,94.0,0.0,94.0,0.0
8,Bột ăn dặm Vinamilk Organic Gold,1.0,0.0,1.0,0.0
9,NaN,0.0,0.0,0.0,NaN
13,Sản phẩm khác,NaN,NaN,NaN,NaN

In [40]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    relevant_BDD.to_excel(writer, index=False, sheet_name='Relevant BDD')

Channel

In [41]:
def process_data_channel(df, columns, nganh_hang, year):
    filtered_df = df[(df["Ngành hàng"] == nganh_hang) & (df["Thời gian"].str.contains(year, na=False))]
    
    grouped_df = filtered_df.groupby(["Sản phẩm"]).agg(columns).sort_values(by="Total new", ascending=False).reset_index().round()
    
    grouped_df['Khác'] = grouped_df["Total new"] - grouped_df.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)
    
    top_13 = grouped_df.head(13)
    khac = grouped_df.iloc[13:].agg(columns).to_frame().transpose()
    
    result_df = pd.concat([top_13, khac], ignore_index=True)
    result_df.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
    result_df.loc[13, 'Khác'] = result_df.loc[13, 'Total new'] - result_df.loc[13, ['Fanpage new', 'FB page new', 'FB user new', 'FB group new', 'Tiktok new', 'Forum new', 'News new', 'Youtube new']].sum()
    result_df = result_df[['Sản phẩm','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
    
    return result_df

# Define columns for Channel
channel_columns = {"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}

# Define nganh_hang values
nganh_hang_list = ['SC', 'SN', 'SB','SĐ','SĐN']

existing_excel_path = r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx"
existing_excel = pd.ExcelFile(existing_excel_path)

# Create Excel writer
with pd.ExcelWriter(existing_excel_path, engine='openpyxl', mode='a') as writer:
    for nganh_hang in nganh_hang_list:
        channel_data = process_data_channel(sh_channel, channel_columns, nganh_hang, year)
        
        # Display the channel_data
        print(f"Channel ({nganh_hang}):")
        print(channel_data)
        print("\n" + "="*50 + "\n")  # Add a separator for better visibility
        
        # Save sentiment_data to the existing Excel file
        sheet_name = f"Channel_{nganh_hang}"
        channel_data.to_excel(writer, sheet_name=sheet_name, index=False)

# Close the existing Excel file
existing_excel.close()

Channel (SC):
                     Sản phẩm  Fanpage new  FB page new  FB user new  \
0           Sữa chua Vinamilk      72805.0     223131.0     488058.0
1              Vinamilk Probi      11327.0     373205.0     223887.0
2               Vinamilk Susu     188239.0     138977.0     212264.0
3               Vinamilk Hero     186721.0     138635.0     210697.0
4                      Yomost      10267.0      94621.0      16537.0
5             Sữa chua Yakult       6461.0      19857.0       3556.0
6              TH True Yogurt       7567.0      12340.0       5667.0
7               Sữa chua Hoff         44.0       5855.0      12217.0
8             Sữa chua TOPKID        911.0       1674.0       1418.0
9                        Veyo       2609.0         40.0       1951.0
10  Sữa chua uống Nestle Yogu          3.0        333.0       3020.0
11      Sữa chua uống LIF KUN         19.0        358.0       2048.0
12                 SC Betagen       1121.0        211.0       1251.0
13              Sản phẩm khác       1317.0       2521.0       8987.0

    FB group new  Tiktok new  Forum new  News new  Youtube new   Khác  \
0        43573.0     14347.0       12.0      21.0        114.0  194.0
1        15579.0     15813.0       24.0       2.0        522.0  220.0
2         1712.0     42934.0        0.0       7.0       4617.0    0.0
3          658.0     42827.0        0.0       7.0       4451.0    0.0
4        16905.0     28635.0        2.0      12.0         76.0    3.0
5         2813.0      6450.0       88.0      46.0        145.0   26.0
6         4014.0       538.0       20.0     123.0         99.0    8.0
7         3874.0       977.0        2.0       0.0          3.0    4.0
8         1578.0         5.0        0.0       0.0         26.0    2.0
9          205.0        12.0        0.0      15.0          0.0    0.0
10         762.0         2.0        0.0       0.0          0.0    0.0
11        1180.0       103.0        0.0       1.0        382.0    1.0
12         555.0       820.0        9.0       0.0         13.0   10.0
13        7300.0       116.0       14.0      69.0        256.0    8.0

    Total new
0    842255.0
1    640579.0
2    588750.0
3    583996.0
4    167058.0
5     39442.0
6     30376.0
7     22976.0
8      5614.0
9      4832.0
10     4120.0
11     4092.0
12     3990.0
13    20588.0

==================================================

Channel (SN):
                     Sản phẩm  Fanpage new  FB page new  FB user new  \
0                        Milo       8035.0     753484.0     792265.0
1                     LOF KUN     147768.0      71232.0     415553.0
2               Vinamilk 100%       1823.0      44086.0     208235.0
3         Vinamilk Green Farm        297.0      31076.0      22280.0
4      Sữa lúa mạch Lof Malto      16489.0       6777.0       6726.0
5       Sữa tươi TH True Milk       4487.0       3554.0       5260.0
6   Sữa tươi Dutch Lady (RTD)       4791.0       3743.0       7417.0
7                    Ovaltine      11902.0        958.0       5274.0
8               Vinamilk Fino       7428.0        637.0       5472.0
9        Sữa tươi Đà Lạt Milk        238.0       2198.0       5308.0
10            Sữa tươi TOPKID       4749.0       1094.0       4406.0
11   Sữa non Colos Fresh Milk       4972.0        796.0       5826.0
12               TH True HILO       1338.0       1760.0       2369.0
13              Sản phẩm khác      17159.0      15871.0      26063.0

    FB group new  Tiktok new  Forum new  News new  Youtube new   Khác  \
0        74257.0     11355.0       18.0     376.0         67.0   10.0
1        24684.0    262890.0       76.0     218.0       5470.0  896.0
2        15638.0      3828.0        0.0       0.0         22.0    0.0
3         1336.0      4917.0        3.0     149.0        200.0   65.0
4         1207.0     19154.0        0.0      25.0       1050.0    2.0
5        22933.0      1509.0      172.0     188.0        132.0   11.0
6        17551.0       818.0       14.0      36.0         40.0    9.0
7          955.0       967.0       21.0       5.0         24.0    1.0
8         3552.0      2345.0        0.0       0.0          7.0    2.0
9         6845.0       457.0        9.0      23.0         41.0   70.0
10        2147.0        50.0        0.0      16.0          4.0    0.0
11         510.0        11.0        0.0       0.0          0.0    7.0
12        4606.0       761.0        5.0      19.0          8.0    7.0
13       22045.0      8405.0       67.0     185.0        242.0  117.0

    Total new
0   1639867.0
1    928787.0
2    273632.0
3     60323.0
4     51430.0
5     38246.0
6     34419.0
7     20107.0
8     19443.0
9     15189.0
10    12466.0
11    12122.0
12    10873.0
13    90154.0

==================================================

Channel (SB):
                     Sản phẩm  Fanpage new  FB page new  FB user new  \
0                   Nuvi Grow    1765008.0      23113.0      38274.0
1                   Grow Plus     146851.0     113542.0     397816.0
2   Vinamilk Dielac Grow Plus       4861.0      18082.0     716925.0
3               Nan Optipro 4      22065.0     228582.0     217372.0
4         Abbott Grow Vietnam     352470.0      10739.0     101738.0
5          Vinamilk Yoko Gold       1797.0      37504.0     306423.0
6               S-26 Ultima 3      93933.0     161322.0      14747.0
7           Pediasure Vietnam      10944.0      42002.0     212056.0
8             Similac Vietnam       2007.0     165248.0       7763.0
9            Vinamilk Optimum       7185.0      17403.0     150936.0
10                        Nan      17490.0      20543.0      34570.0
11      Vinamilk Sure Prevent       5043.0      43094.0     121940.0
12                EnfaGrow A+        678.0     139184.0      15328.0
13              Sản phẩm khác     104872.0     280408.0     562637.0

    FB group new  Tiktok new  Forum new  News new  Youtube new    Khác  \
0        10003.0       972.0        0.0      19.0         11.0    19.0
1       145134.0     17357.0        7.0      24.0        217.0  1116.0
2        34788.0      7506.0        1.0       1.0         14.0     3.0
3        66903.0        76.0        3.0       3.0          3.0     5.0
4        13043.0      1707.0        7.0       2.0          2.0     0.0
5        43894.0       187.0        6.0       3.0          3.0    54.0
6        26415.0      2820.0        1.0       0.0          5.0     1.0
7        30165.0       944.0       64.0       1.0         16.0     2.0
8       108198.0      4324.0       76.0       4.0         42.0     2.0
9        61050.0      5463.0       19.0       1.0         15.0     5.0
10      154149.0      2002.0       20.0       3.0          3.0    55.0
11       12490.0     33825.0        1.0     198.0        281.0     0.0
12       37509.0      1789.0       29.0       5.0         26.0    32.0
13      253352.0     37072.0      343.0     814.0        630.0  1315.0

    Total new
0   1837419.0
1    822064.0
2    782181.0
3    535012.0
4    479708.0
5    389871.0
6    299244.0
7    296194.0
8    287664.0
9    242077.0
10   228835.0
11   216872.0
12   194580.0
13  1241443.0

==================================================

Channel (SĐ):
                        Sản phẩm  Fanpage new  FB page new  FB user new  \
0               Vinamilk Ông thọ       1598.0      90570.0     184769.0
1   Vinamilk Ngôi Sao Phương Nam         19.0       5095.0       3297.0
2             Sữa đặc Dutch Lady          0.0        698.0       3529.0
3               Sữa đặc Vinamilk          0.0        165.0       1772.0
4               Vinamilk Tài lộc          0.0         76.0       1270.0
5               Sữa đặc Nutifood          0.0        160.0        197.0
6               Sữa đặc Hoàn Hảo          0.0          3.0         13.0
7                            NaN          0.0          0.0          0.0
13                 Sản phẩm khác          NaN          NaN          NaN

    FB group new  Tiktok new  Forum new  News new  Youtube new  Khác  \
0       106976.0      5496.0       85.0     443.0       1578.0  94.0
1         6510.0       570.0        8.0      91.0         15.0  10.0
2         2830.0         5.0        3.0       6.0          2.0   0.0
3         4032.0         6.0        1.0       3.0          3.0   0.0
4         1376.0        12.0        0.0       0.0          2.0   2.0
5          416.0         2.0        0.0       4.0          0.0   0.0
6          213.0         0.0        0.0       0.0          0.0   0.0
7            0.0         0.0        0.0       0.0          0.0   NaN
13           NaN         NaN        NaN       NaN          NaN   NaN

    Total new
0    391609.0
1     15615.0
2      7073.0
3      5982.0
4      2738.0
5       779.0
6       229.0
7         0.0
13        NaN

==================================================

Channel (SĐN):
                    Sản phẩm  Fanpage new  FB page new  FB user new  \
0                       Fami      87665.0      15255.0      23359.0
1                TH True Nut       2694.0       1726.0        824.0
2        Vinamilk Hạt Óc Chó       2566.0       1394.0        571.0
3         Vinamilk Super Nut         81.0        452.0       1585.0
4         Vinamilk Hạnh Nhân       2605.0         49.0        118.0
5            Vinamilk Đậu Đỏ       2605.0         47.0        111.0
6      Sữa Đậu Nành Vinamilk       1619.0         42.0        203.0
7      Sữa đậu nành Nutifood          0.0         32.0       1017.0
8         TH True Light Meal        494.0        160.0         72.0
9   Vinamilk Sữa hạt Cao Đạm         76.0         97.0        193.0
10               TH true OAT         18.0        106.0         16.0
11             Nunut Lục Bảo          0.0         18.0         86.0
12      Sữa đậu nành Vinasoy          1.0          5.0         31.0
13             Sản phẩm khác          0.0          3.0         22.0

    FB group new  Tiktok new  Forum new  News new  Youtube new   Khác  \
0        11528.0      1826.0       12.0      94.0        221.0   17.0
1         1692.0        77.0       13.0      43.0         35.0    2.0
2          189.0         1.0        2.0       0.0          2.0    2.0
3         1137.0       676.0        0.0      38.0          2.0  132.0
4           34.0         0.0        0.0       0.0          0.0    1.0
5           35.0         0.0        0.0       0.0          0.0    4.0
6          110.0         0.0        1.0       1.0          1.0    8.0
7          320.0         4.0        0.0       0.0          0.0    0.0
8           73.0         7.0        0.0      23.0         43.0    0.0
9           42.0        53.0        0.0       0.0          0.0    1.0
10          28.0         0.0        0.0       3.0          0.0    3.0
11           7.0         0.0        0.0       0.0          0.0    0.0
12           7.0         0.0        0.0       4.0          0.0    0.0
13           0.0         1.0        0.0       0.0          1.0    2.0

    Total new
0    139977.0
1      7106.0
2      4727.0
3      4103.0
4      2807.0
5      2802.0
6      1985.0
7      1373.0
8       872.0
9       462.0
10      174.0
11      111.0
12       48.0
13       29.0

==================================================

In [42]:
# Channel BDD
filtered_sh_channel_BDD = sh_channel[(sh_channel["Ngành hàng"].isin(bdd)) & (sh_channel["Thời gian"].str.contains(year, na=False))]
channel_BDD = filtered_sh_channel_BDD.groupby(["Sản phẩm"]).agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).sort_values(by="Total new",ascending=False).reset_index().round()  
channel_BDD["Khác"] = channel_BDD["Total new"] - channel_BDD.drop(columns=["Sản phẩm", "Total new"]).sum(axis=1)

channel_BDD_top_13 = channel_BDD.head(13)

SP_khac = channel_BDD.iloc[13:].agg({"Fanpage new": "sum","FB page new": "sum","FB user new": "sum","FB group new": "sum","Tiktok new": "sum","Forum new": "sum","News new": "sum","Youtube new": "sum","Total new": "sum"}).to_frame().transpose()
    
channel_BDD = pd.concat([channel_BDD_top_13, SP_khac], ignore_index=True)
channel_BDD.loc[13, 'Sản phẩm'] = 'Sản phẩm khác'
channel_BDD.loc[13, 'Khác'] = channel_BDD.loc[13, 'Total new'] - channel_BDD.loc[13, ['Fanpage new', 'FB page new', 'FB user new', 'FB group new', 'Tiktok new', 'Forum new', 'News new', 'Youtube new']].sum()
channel_BDD = channel_BDD[['Sản phẩm','Fanpage new','FB page new','FB user new','FB group new','Tiktok new','Forum new','News new','Youtube new','Khác','Total new']]
channel_BDD

,Sản phẩm,Fanpage new,FB page new,FB user new,FB group new,Tiktok new,Forum new,News new,Youtube new,Khác,Total new
0,Gerber,0.0,4562.0,2806.0,745.0,10.0,1.0,0.0,1.0,1.0,8126.0
1,Bột ăn dặm Hipp,34.0,2296.0,2355.0,2690.0,240.0,0.0,0.0,2.0,62.0,7679.0
2,Vinamilk Ridielac,3152.0,1085.0,1622.0,690.0,183.0,0.0,4.0,5.0,1.0,6742.0
3,Bột Dinh Dưỡng Vinamilk,1.0,116.0,242.0,155.0,5.0,0.0,97.0,1.0,0.0,617.0
4,Bột ăn dặm Nuti IQ,0.0,88.0,49.0,70.0,0.0,0.0,0.0,0.0,0.0,207.0
5,Bột ăn dặm Metacare,66.0,58.0,54.0,16.0,8.0,0.0,0.0,0.0,0.0,202.0
6,Cerelac,0.0,24.0,58.0,31.0,1.0,0.0,0.0,1.0,8.0,123.0
7,Bột ăn dặm Vinamilk Optimum Gold,1.0,4.0,13.0,75.0,0.0,0.0,1.0,0.0,0.0,94.0
8,Bột ăn dặm Vinamilk Organic Gold,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
13,Sản phẩm khác,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
with pd.ExcelWriter(r"C:\Users\Kompa-KTelt056\Desktop\Data Kompa\Vinamilk\final.xlsx", engine='openpyxl', mode='a') as writer:
    channel_BDD.to_excel(writer, index=False, sheet_name='Channel BDD')